(function(){'use strict';
function B(){return window.PLANON_UX_BRIDGE} function S(){var b=B(),s=b&&b.state&&b.state();if(!s)return null;s.settings=s.settings||{};var r=s.settings.relationshipThemes;if(!r||typeof r!=='object')r=s.settings.relationshipThemes={couple:{role:'',partnerName:'',plans:[],pages:[],wishes:[]},friend:{mode:'virtual',view:'split',virtual:{name:'라이벌',goalMin:180,paceMin:50},selectedFriendId:'',feed:[],mineSec:0,otherSec:0,running:false,lastTick:0}};r.couple=r.couple||{role:'',partnerName:'',plans:[],pages:[],wishes:[]};r.friend=r.friend||{mode:'virtual',view:'split',virtual:{name:'라이벌',goalMin:180,paceMin:50},selectedFriendId:'',feed:[],mineSec:0,otherSec:0,running:false,lastTick:0};return r}
function M(){var e=window.PLANON_MARKET_THEME;return e&&e.state&&e.state()} function active(){var m=M();return m&&m.active&&m.active.relationTheme||''} function esc(x){return String(x==null?'':x).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]});} function save(){var b=B();if(b&&b.save)b.save()} function toast(x){var b=B();if(b&&b.toast)b.toast(x)}
function icon(k){var d=k==='heart'?'<path d="M12 20s-7-4.5-9-9a5 5 0 0 1 9-4 5 5 0 0 1 9 4c-2 4.5-9 9-9 9Z"/>':k==='users'?'<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2.5 20c.5-4 2.5-6 5.5-6s5 2 5.5 6M14 15c3-1 6 1 6.5 5"/>':'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>';return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+d+'</svg>'}
function chars(role){var mb=window.PLANON_MEONBYEOL;if(!mb)return {me:'',other:''};try{var star=mb.svg('relStar',null,{plain:true,expr:'smile'}),stone=mb.dolSVG({expr:'smile'});return role==='dol'?{me:stone,other:star}:{me:star,other:stone}}catch(e){return {me:'',other:''}}}
function ensureRole(){var r=S();if(active()!=='couple-together-theme'||r.couple.role)return;openCouple('roles')}
function home(){var root=document.querySelector('.home.home-clean');if(!root||root.querySelector('.rel-card'))return;var a=active(),r=S();if(!a||!r)return;var h='';if(a==='couple-together-theme'){var c=r.couple,ch=chars(c.role);h='<section class="rel-card"><div class="rel-head">'+(ch.me||icon('heart'))+'<div><b>애인과 함께</b><small>'+(c.role?'나 '+(c.role==='dol'?'먼돌':'먼별')+' · 애인 '+(c.role==='dol'?'먼별':'먼돌'):'먼별 · 먼돌 역할을 먼저 정해주세요')+'</small></div></div><div class="rel-row" style="margin-top:12px"><button class="rel-btn" data-rel-open="couple">기억의 페이지 열기</button><button class="rel-ghost" data-rel-open="roles">역할 설정</button></div></section>'}else if(a==='friend-together-theme'){h='<section class="rel-card"><div class="rel-head">'+icon('users')+'<div><b>친구랑 함께</b><small>실제 친구 또는 내가 만든 상대와 집중</small></div></div><button class="rel-btn" style="margin-top:12px;width:100%" data-rel-open="friend">Together 열기</button></section>'}root.insertAdjacentHTML('beforeend',h)}
function roleUI(){var r=S().couple,ch=chars(r.role);return '<div class="rel-panel"><div class="rel-box"><h4>먼별 · 먼돌 역할</h4><p class="rel-note">애인과 함께에는 먼별&먼돌 세트가 포함돼요. 둘 중 누가 누구인지 정해야 테마가 적용돼요. 나중에 바꿔도 기억의 페이지 기록은 그대로예요.</p><div class="rel-role"><button class="'+(r.role==='star'?'on':'')+'" data-rel-role="star">'+chars('star').me+'<b>나는 먼별</b><small>애인은 먼돌</small></button><button class="'+(r.role==='dol'?'on':'')+'" data-rel-role="dol">'+chars('dol').me+'<b>나는 먼돌</b><small>애인은 먼별</small></button></div><input class="rel-field" id="rel-partner-name" placeholder="애인 이름 또는 별명" value="'+esc(r.partnerName||'')+'"><button class="rel-btn" style="width:100%" data-rel-save-role>역할 저장</button></div></div>'}
function coupleUI(tab){var c=S().couple, plans=c.plans||[], pages=c.pages||[];if(tab==='roles')return roleUI();if(tab==='pages')return '<div class="rel-panel">'+(pages.length?pages.slice().reverse().map(function(x){return '<article class="rel-page"><div class="date">'+esc(x.date)+'</div><h4>'+esc(x.title||x.place||'우리의 하루')+'</h4><p>'+esc(x.place||'')+'</p><small>'+esc(x.note||'')+'</small></article>'}).join(''):'<div class="rel-box"><h4>첫 페이지를 기다리고 있어요</h4><p class="rel-note">데이트를 마감하면 그날이 한 장의 정본 Page가 되고, 월간 Chapter에 이어져요.</p></div>')+'</div>';if(tab==='tickets')return '<div class="rel-panel">'+(plans.filter(function(x){return x.accepted}).length?plans.filter(function(x){return x.accepted}).slice().reverse().map(function(x){return '<div class="rel-ticket"><small>OUR DATE TICKET</small><h4>'+esc(x.title||'데이트')+'</h4><p>'+esc(x.date+' '+(x.time||'')+' · '+(x.place||'장소 미정'))+'</p></div>'}).join(''):'<div class="rel-box"><h4>아직 발권된 티켓이 없어요</h4><p class="rel-note">데이트를 서로 수락하면 티켓북에 자동으로 들어와요.</p></div>')+'</div>';if(tab==='places'){var pc={};pages.forEach(function(x){if(x.place)pc[x.place]=(pc[x.place]||0)+1});return '<div class="rel-panel"><div class="rel-box"><h4>우리가 간 곳</h4>'+(Object.keys(pc).length?Object.keys(pc).map(function(k){return '<p>'+esc(k)+' · '+pc[k]+'번</p>'}).join(''):'<p class="rel-note">Page에 장소가 쌓이면 우리 장소 기록이 자동으로 생겨요.</p>')+'</div></div>';}if(tab==='wishes')return '<div class="rel-panel"><div class="rel-box"><h4>가고 싶은 곳</h4><div class="rel-row"><input class="rel-field" id="rel-wish" placeholder="다음에 같이 가고 싶은 곳"><button class="rel-btn" data-rel-add-wish>추가</button></div>'+(c.wishes||[]).map(function(x){return '<p>'+esc(x)+'</p>'}).join('')+'</div></div>';if(tab==='chapter'){var groups={};pages.forEach(function(x){var k=(x.date||'').slice(0,7)||'날짜 없음';(groups[k]=groups[k]||[]).push(x)});return '<div class="rel-panel">'+(Object.keys(groups).length?Object.keys(groups).sort().reverse().map(function(k){return '<div class="rel-box"><h4>'+esc(k)+' Chapter</h4><p class="rel-note">'+groups[k].length+'장의 기억 · '+groups[k].map(function(x){return esc(x.place||x.title||'데이트')}).join(' · ')+'</p></div>'}).join(''):'<div class="rel-box">아직 완성된 Chapter가 없어요.</div>')+'</div>';}
return '<div class="rel-panel"><div class="rel-box"><h4>새 데이트 PLAN</h4><div class="rel-row stack390"><input class="rel-field" id="rel-plan-date" type="date"><input class="rel-field" id="rel-plan-time" type="time"></div><input class="rel-field" id="rel-plan-title" placeholder="무엇을 할까요"><input class="rel-field" id="rel-plan-place" placeholder="어디에서 만날까요"><button class="rel-btn" style="width:100%" data-rel-add-plan>데이트 제안 만들기</button></div>'+(plans.length?plans.slice().reverse().map(function(x){return '<div class="rel-ticket"><small>'+(x.accepted?'TICKET · ACCEPTED':'PLAN · 상대 수락 대기')+'</small><h4>'+esc(x.title||'데이트')+'</h4><p>'+esc(x.date+' '+(x.time||'')+' · '+(x.place||'장소 미정'))+'</p><div class="rel-row">'+(!x.accepted?'<button class="rel-ghost" data-rel-accept="'+x.id+'">서로 수락 완료</button>':'<button class="rel-btn" data-rel-close-date="'+x.id+'">데이트 마감 → PAGE</button>')+'</div></div>'}).join(''):'')+'</div>'}
function openCouple(tab){var b=B();if(!b||!b.openModal)return;tab=tab||'plan';b.openModal('<div class="rel-sheet"><h3>애인과 함께</h3><p class="rel-note">기억의 페이지 · PLAN → ACCEPT → TICKET → DATE → PAGE</p><div class="rel-tabs"><button class="'+(tab==='plan'?'on':'')+'" data-rel-couple-tab="plan">데이트</button><button class="'+(tab==='pages'?'on':'')+'" data-rel-couple-tab="pages">기억의 페이지</button><button class="'+(tab==='tickets'?'on':'')+'" data-rel-couple-tab="tickets">티켓북</button><button class="'+(tab==='places'?'on':'')+'" data-rel-couple-tab="places">우리가 간 곳</button><button class="'+(tab==='wishes'?'on':'')+'" data-rel-couple-tab="wishes">가고 싶은 곳</button><button class="'+(tab==='chapter'?'on':'')+'" data-rel-couple-tab="chapter">Chapter</button><button class="'+(tab==='roles'?'on':'')+'" data-rel-couple-tab="roles">먼별·먼돌</button></div><div id="rel-body">'+coupleUI(tab)+'</div></div>')}
function fmt(sec){sec=Math.max(0,Math.floor(sec||0));return String(Math.floor(sec/3600)).padStart(2,'0')+':'+String(Math.floor(sec%3600/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function friendName(){var f=S().friend;if(f.mode==='virtual')return f.virtual&&f.virtual.name||'라이벌';var fs=B()&&B().friendState&&B().friendState(),x=(fs&&fs.friends||[]).find(function(z){return String(z.id)===String(f.selectedFriendId)});return x&&(x.name||x.code)||'친구'}
function actualCharacter(id,own){
  try{var s=window.PLANON_MB_SOCIAL,h=s&&s.avatarFace?s.avatarFace(id,!!own):'';if(h)return h;}catch(e){}
  try{if(typeof window.nemoSVG==='function')return window.nemoSVG('basic','');}catch(e){}
  return icon('users');
}
function friendUI(){
  var f=S().friend,fs=B()&&B().friendState&&B().friendState(),friends=fs&&fs.friends||[],nm=friendName(),acc=B()&&B().account&&B().account(),myId=acc&&acc.uid||'';
  var chosen=f.mode==='real'?friends.find(function(x){return String(x.id)===String(f.selectedFriendId)}):null;
  var meFace=actualCharacter(myId,true),otherFace=f.mode==='real'?actualCharacter(chosen&&chosen.id,false):icon('users');
  var me='<div class="rel-person"><div class="rel-character">'+meFace+'</div><b>나</b><div class="rel-time">'+fmt(f.mineSec)+'</div><small>'+(f.running?'집중 중':'오늘 집중')+'</small></div>',
      other='<div class="rel-person"><div class="rel-character">'+otherFace+'</div><b>'+esc(nm)+'</b><div class="rel-time">'+fmt(f.otherSec)+'</div><small>'+(f.mode==='virtual'?'설정한 페이스 기준 시뮬레이션':'친구가 공유한 집중 시간')+'</small></div>';
  var stage=f.view==='mine'?me:f.view==='other'?other:'<div class="rel-duo">'+me+other+'</div>';
  return '<div class="rel-panel"><div class="rel-box"><h4>함께할 상대</h4><div class="rel-row"><button class="rel-ghost" data-rel-fmode="virtual">'+(f.mode==='virtual'?'● ':'')+'내가 만든 상대</button><button class="rel-ghost" data-rel-fmode="real">'+(f.mode==='real'?'● ':'')+'친구</button></div>'+(f.mode==='virtual'?'<input class="rel-field" id="rel-virtual-name" value="'+esc(f.virtual.name||'')+'" placeholder="상대 이름"><div class="rel-row"><input class="rel-field" id="rel-virtual-goal" type="number" min="10" max="1440" value="'+Number(f.virtual.goalMin||180)+'" placeholder="오늘 목표 분"><input class="rel-field" id="rel-virtual-pace" type="number" min="5" max="180" value="'+Number(f.virtual.paceMin||50)+'" placeholder="집중 페이스 분"></div><button class="rel-ghost" data-rel-save-virtual>상대 설정 저장</button>':'<select class="rel-field" id="rel-real-friend"><option value="">친구 선택</option>'+friends.map(function(x){return '<option value="'+esc(x.id)+'" '+(String(x.id)===String(f.selectedFriendId)?'selected':'')+'>'+esc(x.name||x.code||'친구')+'</option>'}).join('')+'</select><p class="rel-note">친구 모드에서는 각자 설정한 캐릭터를 그대로 보여주고, 공유된 집중 시간과 클리어만 받아와요.</p>')+'</div><div class="rel-switch"><button class="'+(f.view==='mine'?'on':'')+'" data-rel-view="mine">나만</button><button class="'+(f.view==='split'?'on':'')+'" data-rel-view="split">분할</button><button class="'+(f.view==='other'?'on':'')+'" data-rel-view="other">친구만</button></div>'+stage+'<div class="rel-row"><button class="rel-btn" data-rel-timer>'+(f.running?'집중 멈추기':'같이 집중 시작')+'</button><button class="rel-ghost" data-rel-clear>할 일 클리어</button></div><div class="rel-box"><h4>오늘 같이 공부</h4><div class="rel-row"><b>'+fmt(f.mineSec)+'</b><span style="text-align:center">—</span><b style="text-align:right">'+fmt(f.otherSec)+'</b></div><p class="rel-note">기본은 화면 분할 · 위 스위치로 나만/친구만 볼 수도 있어요. 둘이 합쳐 '+fmt((f.mineSec||0)+(f.otherSec||0))+' 집중했어요.</p></div><div class="rel-feed">'+(f.feed||[]).slice(-4).reverse().map(function(x){return '<div>'+esc(x.text)+'</div>'}).join('')+'</div></div>';
}
function openFriend(){var b=B();if(b&&b.openModal)b.openModal('<div class="rel-sheet"><h3>친구랑 함께</h3><p class="rel-note">실제 친구 또는 가상 상대와 집중 · 기본 컬러 이모지는 사용하지 않아요.</p><div id="rel-body">'+friendUI()+'</div></div>')}
function rerenderFriend(){var x=document.getElementById('rel-body');if(x)x.innerHTML=friendUI()}
function tick(){var r=S();if(!r||!r.friend.running)return;var f=r.friend,now=Date.now(),dt=Math.min(5,Math.max(0,(now-(f.lastTick||now))/1000));f.lastTick=now;f.mineSec=(f.mineSec||0)+dt;if(f.mode==='virtual'){var pace=Math.max(5,Number(f.virtual.paceMin||50));var ratio=Math.min(.96,.72+(pace%17)/100);f.otherSec=(f.otherSec||0)+dt*ratio}save();rerenderFriend()}
setInterval(tick,1000);

function syncReal(){var r=S();if(!r||r.friend.mode!=='real'||!r.friend.selectedFriendId)return;var b=B(),db=b&&b.db&&b.db(),acc=b&&b.account&&b.account();if(!db||!acc||!acc.uid)return;var f=r.friend,payload={running:!!f.running,focusSec:Math.floor(f.mineSec||0),lastClear:(f.feed&&f.feed.length?f.feed[f.feed.length-1]:null),updatedAt:Date.now()};db.from('planner_friend_data').upsert({owner_id:acc.uid,friend_id:f.selectedFriendId,kind:'together',payload:payload,updated_at:new Date().toISOString()},{onConflict:'owner_id,friend_id,kind'}).then(function(){}).catch(function(){});db.from('planner_friend_data').select('payload,updated_at').eq('owner_id',f.selectedFriendId).eq('friend_id',acc.uid).eq('kind','together').maybeSingle().then(function(x){if(x&&x.data&&x.data.payload){var q=x.data.payload;f.otherSec=Number(q.focusSec||0);if(q.lastClear&&q.lastClear.at&&!(f.feed||[]).some(function(z){return z.remoteAt===q.lastClear.at})){f.feed=f.feed||[];f.feed.push({at:Date.now(),remoteAt:q.lastClear.at,text:friendName()+'님이 할 일 하나를 클리어했어요'});}save();rerenderFriend();}}).catch(function(){});}
setInterval(syncReal,3000);

function closeDate(id){var c=S().couple,x=(c.plans||[]).find(function(z){return z.id===id});if(!x)return;var note=prompt('오늘을 한 줄로 남겨주세요')||'';c.pages=c.pages||[];if(!c.pages.some(function(p){return p.planId===id}))c.pages.push({id:'page-'+Date.now(),planId:id,date:x.date||new Date().toISOString().slice(0,10),title:x.title,place:x.place,note:note,createdAt:Date.now()});x.closed=true;save();toast('오늘이 기억의 페이지 한 장으로 남았어요');openCouple('pages')}
document.addEventListener('click',function(e){var a=e.target.closest&&e.target.closest('[data-rel-open],[data-rel-role],[data-rel-save-role],[data-rel-couple-tab],[data-rel-add-plan],[data-rel-accept],[data-rel-close-date],[data-rel-fmode],[data-rel-save-virtual],[data-rel-view],[data-rel-timer],[data-rel-clear],[data-rel-add-wish]');if(!a)return;if(a.dataset.relOpen){a.dataset.relOpen==='friend'?openFriend():openCouple(a.dataset.relOpen==='roles'?'roles':'plan');return}if(a.dataset.relCoupleTab){document.getElementById('rel-body').innerHTML=coupleUI(a.dataset.relCoupleTab);return}if(a.dataset.relRole){S().couple.role=a.dataset.relRole;save();openCouple('roles');return}if(a.hasAttribute('data-rel-save-role')){var c=S().couple,n=document.getElementById('rel-partner-name');c.partnerName=n?n.value.trim():c.partnerName;if(!c.role){toast('먼별과 먼돌 역할을 먼저 골라주세요');return}save();toast('우리 역할을 저장했어요');openCouple('plan');return}if(a.hasAttribute('data-rel-add-wish')){var c=S().couple,w=document.getElementById('rel-wish');if(w&&w.value.trim()){c.wishes=c.wishes||[];c.wishes.push(w.value.trim());save();openCouple('wishes')}return}if(a.hasAttribute('data-rel-add-plan')){var c=S().couple,d=document.getElementById('rel-plan-date'),t=document.getElementById('rel-plan-time'),n=document.getElementById('rel-plan-title'),p=document.getElementById('rel-plan-place');if(!d||!d.value){toast('데이트 날짜를 정해주세요');return}c.plans=c.plans||[];c.plans.push({id:'plan-'+Date.now(),date:d.value,time:t&&t.value||'',title:n&&n.value.trim()||'데이트',place:p&&p.value.trim()||'',accepted:false});save();openCouple('plan');return}if(a.dataset.relAccept){var x=(S().couple.plans||[]).find(function(z){return z.id===a.dataset.relAccept});if(x)x.accepted=true;save();openCouple('plan');return}if(a.dataset.relCloseDate){closeDate(a.dataset.relCloseDate);return}if(a.dataset.relFmode){S().friend.mode=a.dataset.relFmode;save();rerenderFriend();return}if(a.hasAttribute('data-rel-save-virtual')){var f=S().friend,n=document.getElementById('rel-virtual-name'),g=document.getElementById('rel-virtual-goal'),p=document.getElementById('rel-virtual-pace');f.virtual={name:n&&n.value.trim()||'라이벌',goalMin:Number(g&&g.value||180),paceMin:Number(p&&p.value||50)};save();rerenderFriend();return}if(a.dataset.relView){S().friend.view=a.dataset.relView;save();rerenderFriend();return}if(a.hasAttribute('data-rel-timer')){var f=S().friend;f.running=!f.running;f.lastTick=Date.now();f.feed=f.feed||[];f.feed.push({at:Date.now(),text:f.running?'집중을 시작했어요':'집중을 마쳤어요'});save();rerenderFriend();return}if(a.hasAttribute('data-rel-clear')){var f=S().friend;f.feed=f.feed||[];f.feed.push({at:Date.now(),text:'내가 할 일 하나를 클리어했어요'});save();rerenderFriend();return}});
document.addEventListener('change',function(e){if(e.target&&e.target.id==='rel-real-friend'){S().friend.selectedFriendId=e.target.value;save();rerenderFriend()}});
window.addEventListener('planon-market-change',function(){setTimeout(function(){home();ensureRole()},30)});var main=document.getElementById('main');if(main)new MutationObserver(function(){setTimeout(home,20)}).observe(main,{childList:true});setTimeout(function(){home();ensureRole()},100);
window.PLANON_RELATION_THEME={openCouple:openCouple,openFriend:openFriend};})();