-- PLAN:ON Friend ID + stronger blocking (2026-09-27)
-- Safe to run repeatedly.
begin;

create table if not exists public.planner_user_ids (
  user_id uuid primary key references auth.users(id) on delete cascade,
  handle text not null unique,
  updated_at timestamptz not null default now(),
  check (handle ~ '^[a-z0-9][a-z0-9._]{2,14}[a-z0-9]$'),
  check (char_length(handle) between 4 and 16)
);

create table if not exists public.planner_user_id_changes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  old_handle text not null,
  new_handle text not null,
  changed_at timestamptz not null default now()
);
create index if not exists idx_planner_user_id_changes_user_time on public.planner_user_id_changes(user_id,changed_at desc);
create index if not exists idx_planner_user_id_changes_old_time on public.planner_user_id_changes(old_handle,changed_at desc);

alter table public.planner_user_ids enable row level security;
alter table public.planner_user_id_changes enable row level security;

drop policy if exists planner_user_ids_own_read on public.planner_user_ids;
create policy planner_user_ids_own_read on public.planner_user_ids for select to authenticated using(user_id=auth.uid());
drop policy if exists planner_user_id_changes_own_read on public.planner_user_id_changes;
create policy planner_user_id_changes_own_read on public.planner_user_id_changes for select to authenticated using(user_id=auth.uid());

create or replace function public.planner_users_blocked(a uuid,b uuid)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.planner_user_blocks x
    where (x.blocker_id=a and x.blocked_id=b) or (x.blocker_id=b and x.blocked_id=a));
$$;
revoke all on function public.planner_users_blocked(uuid,uuid) from public;
grant execute on function public.planner_users_blocked(uuid,uuid) to authenticated;

create or replace function public.planner_my_user_id_info()
returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid(); h text; n int:=0; first_change timestamptz;
begin
  if u is null then raise exception 'not_authenticated'; end if;
  select handle into h from public.planner_user_ids where user_id=u;
  select count(*),min(changed_at) into n,first_change from public.planner_user_id_changes where user_id=u and changed_at>now()-interval '14 days';
  return jsonb_build_object('handle',coalesce(h,''),'changes_left',greatest(0,2-n),'reset_at',case when first_change is null then null else first_change+interval '14 days' end);
end;
$$;

create or replace function public.planner_set_user_id(h text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid(); v text:=lower(trim(coalesce(h,''))); old text; n int:=0; first_change timestamptz;
begin
  if u is null then raise exception 'not_authenticated'; end if;
  if char_length(v)<4 or char_length(v)>16 or v !~ '^[a-z0-9][a-z0-9._]{2,14}[a-z0-9]$' then raise exception 'invalid_handle'; end if;
  if v in ('admin','administrator','planon','plan.on','support','official','help','root','system') then raise exception 'handle_reserved'; end if;
  select handle into old from public.planner_user_ids where user_id=u for update;
  if old=v then return public.planner_my_user_id_info(); end if;
  if exists(select 1 from public.planner_user_ids where handle=v and user_id<>u) then raise exception 'handle_taken'; end if;
  if exists(select 1 from public.planner_user_id_changes where old_handle=v and user_id<>u and changed_at>now()-interval '30 days') then raise exception 'handle_reserved'; end if;
  if old is not null then
    select count(*),min(changed_at) into n,first_change from public.planner_user_id_changes where user_id=u and changed_at>now()-interval '14 days';
    if n>=2 then raise exception 'handle_change_limit'; end if;
    insert into public.planner_user_id_changes(user_id,old_handle,new_handle) values(u,old,v);
  end if;
  insert into public.planner_user_ids(user_id,handle,updated_at) values(u,v,now())
    on conflict(user_id) do update set handle=excluded.handle,updated_at=excluded.updated_at;
  return public.planner_my_user_id_info();
exception when unique_violation then raise exception 'handle_taken';
end;
$$;

create or replace function public.planner_resolve_user_id(h text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare u uuid:=auth.uid(); v text:=lower(trim(coalesce(h,''))); target uuid;
begin
  if u is null then raise exception 'not_authenticated'; end if;
  select user_id into target from public.planner_user_ids where handle=v;
  if target is null or target=u or public.planner_users_blocked(u,target) then return null; end if;
  return jsonb_build_object('user_id',target,'handle',v);
end;
$$;

revoke all on function public.planner_my_user_id_info() from public;
revoke all on function public.planner_set_user_id(text) from public;
revoke all on function public.planner_resolve_user_id(text) from public;
grant execute on function public.planner_my_user_id_info(),public.planner_set_user_id(text),public.planner_resolve_user_id(text) to authenticated;
grant select on public.planner_user_ids,public.planner_user_id_changes to authenticated;

-- Blocking must prevent reconnecting or sending a new appointment request.
drop policy if exists invites_insert on public.planner_friend_invites;
create policy invites_insert on public.planner_friend_invites for insert to authenticated
  with check(from_user=auth.uid() and to_user<>auth.uid() and status='pending' and not public.planner_users_blocked(from_user,to_user));
drop policy if exists appointment_insert on public.planner_appointment_requests;
create policy appointment_insert on public.planner_appointment_requests for insert to authenticated
  with check(from_user=auth.uid() and to_user<>auth.uid() and status='pending' and not public.planner_users_blocked(from_user,to_user));

commit;
