(function(){'use strict';var B=window.PLANON_UX_BRIDGE,D=window.PLANON_SMART_DATA,U=window.PLANON_UNDO;if(!B||!D)return;
var proposal=null;function uid(){try{return crypto.randomUUID();}catch(e){return 'sp-'+Date.now()+'-'+Math.random().toString(36).slice(2);}}function S(){return B.state();}function pad(n){return String(n).padStart(2,'0');}function dk(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}function pd(k){var p=k.split('-').map(Number);return new Date(p[0],p[1]-1,p[2]);}function add(d,n){var x=new Date(d);x.setDate(x.getDate()+n);return x;}function min(t){var p=String(t||'').split(':');return (+p[0]||0)*60+(+p[1]||0);}function hm(n){return pad(Math.floor(n/60))+':'+pad(n%60);}function today(){return B.todayKey();}function esc(x){return String(x==null?'':x).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}function dur(n){n=Math.round(n);return n>=60?Math.floor(n/60)+'시간'+(n%60?' '+n%60+'분':''):n+'분';}
function eventOn(e,k,d){if(e.date===k)return true;if(Array.isArray(e.days)){var w=(d.getDay()+6)%7;return e.days.indexOf(w)>=0&&(!e.from||k>=e.from)&&(!e.to||k<=e.to);}return e.from&&e.to&&k>=e.from&&k<=e.to;}
function busy(k,ignore){var st=S(),d=pd(k),w=(d.getDay()+6)%7,a=[];(st.classes||[]).forEach(function(c){if(c.day===w&&c.start&&c.end&&(!c.from||k>=c.from)&&(!c.to||k<=c.to))a.push([min(c.start),min(c.end)]);});(st.events||[]).forEach(function(e){if(e.id===ignore||!e.start||!eventOn(e,k,d))return;var en=e.end?min(e.end):min(e.start)+60;a.push([min(e.start),en]);});(st.todos||[]).forEach(function(t){if(t.id===ignore||t.done||t.scope!=='day'||t.key!==k||!t.time)return;a.push([min(t.time),min(t.time)+Math.max(20,Number(t.dur||t.estimatedMinutes||40))]);});(st.exams||[]).forEach(function(e){if((e.start===k||e.end===k)&&e.time)a.push([min(e.time),min(e.time)+Number(e.dur||120)]);});a.sort(function(x,y){return x[0]-y[0];});return a;}
function gaps(k,ignore){var p=D.prefs(),start=8*60,end=22*60,b=busy(k,ignore),out=[],cur=start;b.forEach(function(x){if(x[0]>cur)out.push([cur,Math.min(x[0],end)]);cur=Math.max(cur,x[1]);});if(cur<end)out.push([cur,end]);out=out.filter(function(x){return x[1]-x[0]>=20;});var total=out.reduce(function(n,x){return n+x[1]-x[0];},0),allowed=Math.min(Number(p.dailyMaxMin||240),Math.floor(total*(100-Number(p.bufferPct||20))/100)),used=0,res=[];out.forEach(function(x){if(used>=allowed)return;var len=Math.min(x[1]-x[0],allowed-used);if(len>=20){res.push([x[0],x[0]+len]);used+=len;}});return res;}
function plan(minutes,due,from,ignore){var left=Math.max(0,minutes),out=[],d=pd(from||today()),end=pd(due||today()),days=[];while(d<=end){var k=dk(d),gs=gaps(k,ignore);if(gs.length)days.push({date:k,gaps:gs});d=add(d,1);}for(var di=0;di<days.length&&left>=20;di++){var remainDays=Math.max(1,days.length-di),target=Math.max(30,Math.min(60,Math.ceil((left/remainDays)/5)*5)),gs=days[di].gaps;for(var gi=0;gi<gs.length;gi++){var cap=gs[gi][1]-gs[gi][0],take=Math.min(target,left,cap);if(take>=20){out.push({date:days[di].date,start:gs[gi][0],end:gs[gi][0]+take,dur:take});left-=take;break;}}}/* 큰 과제는 1차로 날짜별 분산 후 남은 양만 두 번째 블록으로 채웁니다. */for(var dj=0;dj<days.length&&left>=20;dj++){var gs2=gaps(days[dj].date,ignore);for(var gj=0;gj<gs2.length&&left>=20;gj++){var cap2=gs2[gj][1]-gs2[gj][0],take2=Math.min(60,left,cap2);if(take2>=20){out.push({date:days[dj].date,start:gs2[gj][0],end:gs2[gj][0]+take2,dur:take2});left-=take2;}}}return {blocks:out,remaining:left};}
function movable(t){return t&&t.movable!==false&&t.autoScheduleEnabled!==false;}
function missed(){var tk=today();return (S().todos||[]).filter(function(t){return t&&!t.done&&t.scope==='day'&&t.key&&t.key<tk&&movable(t);});}
function groupMinutes(xs){return xs.reduce(function(n,t){return n+Math.max(20,Number(t.dur||t.remainingMinutes||t.estimatedMinutes||40));},0);}
function buildMissed(mode,ids){var xs=missed().filter(function(t){return !ids||ids.indexOf(t.id)>=0;});if(!xs.length)return null;var changes=[],tk=today();xs.forEach(function(t){var need=Math.max(20,Number(t.dur||40)),due=t.due&&t.due>=tk?t.due:(mode==='today'?tk:dk(add(pd(tk),6))),d=pd(tk),end=pd(due),found=null;while(d<=end&&!found){var k=dk(d),gs=gaps(k,t.id);for(var i=0;i<gs.length;i++){if(gs[i][1]-gs[i][0]>=need){found={date:k,start:gs[i][0],dur:need};break;}}d=add(d,1);}if(found)changes.push({id:t.id,before:{date:t.key,time:t.time||'',dur:need},after:{date:found.date,time:hm(found.start),dur:need},title:t.text});});return {reason:'미완료 일정 재배치',changes:changes};}
function splitProposal(id){var t=(S().todos||[]).find(function(x){return x.id===id;});if(!t||t.done||!t.due)return null;var total=Math.max(20,Number(t.estimatedMinutes||t.estimateMin||t.remainingMinutes||0));if(!total)return null;var r=plan(total,t.due,today(),t.id);if(r.remaining>0)return {reason:'과제 자동 분할',changes:[],remaining:r.remaining};return {reason:'과제 자동 분할',parentId:t.id,changes:r.blocks.map(function(b,i){return {create:true,parentId:t.id,title:t.text+' · '+(i+1),after:{date:b.date,time:hm(b.start),dur:b.dur}};})};}
function preview(p){if(!p||!p.changes.length){B.toast('옮길 수 있는 빈 시간이 없어요');return;}proposal=p;var rows=p.changes.map(function(c,i){return '<div class="smart-change"><div><b>'+esc(c.title)+'</b><small>'+(c.create?'새 공부 블록':esc(c.before.date)+' '+esc(c.before.time||'시간 미정')+' →')+'</small></div><div class="smart-edit"><input type="date" data-smart-date="'+i+'" value="'+c.after.date+'"><input type="time" data-smart-time="'+i+'" value="'+c.after.time+'"></div></div>';}).join('');B.openModal('<h3>계획을 조금 조정할까요?</h3><p class="hint">추천안만 만들었어요. 아직 일정은 바뀌지 않았어요.</p><div class="smart-changes">'+rows+'</div><div class="acts"><button class="b-ghost" data-smart="cancel">취소</button><button class="tbtn" data-smart="edit">직접 수정</button><button class="b-save" data-smart="apply">적용하기</button></div>');}
function apply(){if(!proposal)return;var st=S();if(U)U.capture(proposal.reason);proposal.changes.forEach(function(c,i){var di=document.querySelector('[data-smart-date="'+i+'"]'),ti=document.querySelector('[data-smart-time="'+i+'"]'),date=di&&di.value||c.after.date,time=ti&&ti.value||c.after.time;if(c.create){var p=(st.todos||[]).find(function(x){return x.id===c.parentId;});if(!p)return;var id=uid(),child={id:id,text:c.title,done:false,scope:'day',key:date,time:time,dur:c.after.dur,due:p.due,course:p.course||'',movable:true,autoScheduleEnabled:true,autoGenerated:true,source:'auto-split',splitParentId:p.id,splitIndex:(p.planChildIds||[]).length+1,created:Date.now()+i,order:Date.now()+i};st.todos.push(child);p.planChildIds=p.planChildIds||[];p.planChildIds.push(id);p.planTotalMin=Number(p.estimatedMinutes||p.estimateMin||0);p.remainingMinutes=p.planTotalMin;return;}var t=(st.todos||[]).find(function(x){return x.id===c.id;});if(!t||!movable(t))return;t.key=date;t.time=time;t.dur=c.after.dur;t.scope='day';t.rescheduledAt=Date.now();t.missedAt=null;});B.save();if(U){U.seal();U.show();}proposal=null;B.closeModal();B.render(true);}
function risk(t){var rem=Math.max(0,Number(t.remainingMinutes||t.estimatedMinutes||t.estimateMin||t.planTotalMin||0));if(Array.isArray(t.planChildIds)){var kids=(S().todos||[]).filter(function(x){return x.splitParentId===t.id;}),done=kids.filter(function(x){return x.done;}).reduce(function(n,x){return n+Number(x.dur||0);},0);rem=Math.max(0,rem-done);}if(rem<20||!t.due)return null;var cap=0,d=pd(today()),e=pd(t.due);while(d<=e){cap+=gaps(dk(d),t.id).reduce(function(n,g){return n+g[1]-g[0];},0);d=add(d,1);}var ratio=cap?rem/cap:99,level=rem>cap?'danger':ratio>.75?'warn':'safe';return {task:t,remaining:rem,capacity:cap,shortage:Math.max(0,rem-cap),level:level};}
function risks(){return (S().todos||[]).filter(function(t){return !t.done&&!t.splitParentId&&t.due&&movable(t);}).map(risk).filter(Boolean).sort(function(a,b){return b.shortage-a.shortage;});}
function recommend(){var tk=today(),now=new Date(),m=now.getHours()*60+now.getMinutes(),free=gaps(tk),cur=free.find(function(g){return m>=g[0]&&m<g[1];})||free.find(function(g){return g[0]>m;});if(!cur)return null;var avail=cur[1]-Math.max(cur[0],m),rs=risks();var cand=(S().todos||[]).filter(function(t){return !t.done&&movable(t)&&(t.scope!=='day'||!t.key||t.key<=tk)&&Math.max(20,Number(t.remainingMinutes||t.dur||t.estimatedMinutes||40))<=avail+15;});cand.sort(function(a,b){var ra=rs.find(function(x){return x.task.id===a.id;}),rb=rs.find(function(x){return x.task.id===b.id;});return (rb&&rb.level==='danger'?100:0)-(ra&&ra.level==='danger'?100:0)||String(a.due||'9999').localeCompare(String(b.due||'9999'));});return cand[0]?{task:cand[0],available:avail}:null;}
window.PLANON_SCHEDULING={gaps:gaps,plan:plan,missed:missed,buildMissed:buildMissed,splitProposal:splitProposal,preview:preview,apply:apply,risks:risks,recommend:recommend,movable:movable,dur:dur};
document.addEventListener('click',function(e){var a=e.target.closest&&e.target.closest('[data-smart]');if(!a)return;if(a.dataset.smart==='apply')apply();if(a.dataset.smart==='cancel'){proposal=null;B.closeModal();}if(a.dataset.smart==='edit')B.toast('추천 날짜와 시간을 직접 바꾼 뒤 적용하면 돼요');});
})();
