(function(){
'use strict';
var B=window.PLANON_UX_BRIDGE;if(!B)return;
var CACHE={data:null,at:0,lastAttempt:0,lat:null,lon:null,accuracy:null,pending:false,error:'',permission:'unknown'};
var REFRESH_MS=20*60*1000, MAX_ACCURACY_M=12000;
function state(){return B.state&&B.state();}
function ui(){return B.ui&&B.ui();}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function enabled(){var s=state();return !!(s&&s.settings&&s.settings.weatherOn!==false);}
function ensureDefault(){var s=state();if(!s||!s.settings)return;if(s.settings.weatherOn===undefined){s.settings.weatherOn=true;B.save();}}
function wxIcon(name,cls){
  var c=cls||'wx-ico';
  var open='<svg class="'+c+'" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">';
  if(name==='sun')return open+'<circle cx="12" cy="12" r="3.5"/><path d="M12 2.8v2.1M12 19.1v2.1M2.8 12h2.1M19.1 12h2.1M5.5 5.5 7 7M17 17l1.5 1.5M18.5 5.5 17 7M7 17l-1.5 1.5"/></svg>';
  if(name==='partly')return open+'<circle cx="8" cy="8" r="3"/><path d="M8 2.7v1.2M2.7 8h1.2M4.3 4.3l.9.9M10.8 5.2l.9-.9"/><path d="M8 17.8h9.2a3.3 3.3 0 0 0 .2-6.6 5.1 5.1 0 0 0-9.7 1.5A2.6 2.6 0 0 0 8 17.8Z"/></svg>';
  if(name==='cloud')return open+'<path d="M6.2 18h11.2a3.6 3.6 0 0 0 .2-7.2 5.6 5.6 0 0 0-10.7 1.7A2.8 2.8 0 0 0 6.2 18Z"/></svg>';
  if(name==='fog')return open+'<path d="M4 8.5h16M6 12h12M4 15.5h16"/></svg>';
  if(name==='drizzle')return open+'<path d="M6.2 14.3h11.2a3.2 3.2 0 0 0 .2-6.4 5.3 5.3 0 0 0-10.1 1.5 2.5 2.5 0 0 0-1.3 4.9Z"/><path d="M8 17.2l-.5 1M12 17.2l-.5 1M16 17.2l-.5 1"/></svg>';
  if(name==='rain')return open+'<path d="M6.2 13.8h11.2a3.2 3.2 0 0 0 .2-6.4 5.3 5.3 0 0 0-10.1 1.5 2.5 2.5 0 0 0-1.3 4.9Z"/><path d="M8.5 16.5l-1 2.2M12.5 16.5l-1 2.2M16.5 16.5l-1 2.2"/></svg>';
  if(name==='snow')return open+'<path d="M6.2 13.5h11.2a3.2 3.2 0 0 0 .2-6.4 5.3 5.3 0 0 0-10.1 1.5 2.5 2.5 0 0 0-1.3 4.9Z"/><path d="M8 17h.01M12 18.5h.01M16 17h.01"/></svg>';
  if(name==='storm')return open+'<path d="M6.2 13.3h11.2a3.2 3.2 0 0 0 .2-6.4 5.3 5.3 0 0 0-10.1 1.5 2.5 2.5 0 0 0-1.3 4.9Z"/><path d="m13.5 14.8-3 4h2l-1 2.2"/></svg>';
  if(name==='umbrella')return open+'<path d="M4 11a8 8 0 0 1 16 0H4Z"/><path d="M12 11v6.2a2 2 0 0 0 4 0"/><path d="M12 3V2"/></svg>';
  if(name==='location')return open+'<path d="M12 21s6-5.4 6-11a6 6 0 1 0-12 0c0 5.6 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg>';
  if(name==='refresh')return open+'<path d="M19 7v5h-5"/><path d="M18 12a6.5 6.5 0 1 1-1.9-4.6L19 10"/></svg>';
  return wxIcon('cloud',cls);
}
function addStyles(){if(document.getElementById('planon-weather-css'))return;var st=document.createElement('style');st.id='planon-weather-css';st.textContent=`
.wx-inline{display:flex;align-items:center;gap:6px;margin-top:4px;min-width:0;flex-wrap:wrap}.wx-chip,.wx-umbrella{height:28px;padding:0 9px;border-radius:999px;background:var(--soft);font-size:12px;font-weight:800;white-space:nowrap;display:inline-flex;align-items:center;gap:5px}.wx-chip.loading{font-weight:650;color:var(--sub)}.wx-umbrella{background:color-mix(in srgb,var(--planner-color) 50%,var(--card));color:var(--ink)}.wx-chip.warn{color:var(--now)}.wx-title-weather{display:inline-flex;align-items:center;gap:4px;margin-left:5px;padding:1px 7px;border-radius:999px;background:color-mix(in srgb,var(--planner-color) 24%,var(--card));color:var(--ink);font-size:11px;font-weight:800;line-height:22px;vertical-align:1px;white-space:nowrap}.wx-title-weather.rain{background:color-mix(in srgb,var(--planner-color) 52%,var(--card))}.wx-title-weather.connect{background:var(--soft);color:var(--sub)}.wx-title-weather .wx-ico{width:14px;height:14px}.wx-ico{width:16px;height:16px;display:block;flex:none}.wx-big-ico{width:42px;height:42px;display:block}.wx-hour-ico{width:20px;height:20px;display:block;margin:5px auto 3px}.wx-btn-ico{width:15px;height:15px;display:block;flex:none}
.wx-settings{margin-top:10px}.wx-status{font-size:12px;color:var(--sub);line-height:1.5}.wx-status.bad{color:var(--now)}.wx-settings .tbtn{display:inline-flex;align-items:center;justify-content:center;gap:5px}
.wx-hero{display:flex;align-items:center;gap:14px;padding:8px 2px 14px}.wx-big{width:44px;height:44px;display:grid;place-items:center}.wx-nowcopy{min-width:0}.wx-temp{font-size:30px;font-weight:850;letter-spacing:-.04em}.wx-desc{font-size:13px;color:var(--sub);margin-top:2px}.wx-raincard{padding:12px 13px;border-radius:14px;background:color-mix(in srgb,var(--planner-color) 46%,var(--card));margin:0 0 12px}.wx-raincard b{display:flex;align-items:center;gap:6px;font-size:14px}.wx-raincard small{display:block;margin-top:4px;color:var(--sub);line-height:1.5}.wx-hourly{display:flex;gap:7px;overflow-x:auto;padding:2px 0 8px;scrollbar-width:none}.wx-hourly::-webkit-scrollbar{display:none}.wx-hour{flex:0 0 72px;padding:10px 7px;border-radius:13px;background:var(--soft);text-align:center}.wx-hour b,.wx-hour small{display:block}.wx-hour b{font-size:12px}.wx-hour small{font-size:11px;color:var(--sub);line-height:1.35}.wx-note{margin:10px 0 0;color:var(--sub);font-size:11px;line-height:1.55}.wx-actions{display:flex;gap:8px;margin-top:12px}.wx-actions button{flex:1;height:42px;border-radius:12px;background:var(--soft);font-weight:750;text-align:center;display:flex;align-items:center;justify-content:center;gap:6px}.wx-actions .pri{background:var(--planner-color);color:var(--planner-ink,#1c1c1e)}
`;
document.head.appendChild(st);}
function codeMeta(code){code=Number(code);if(code===0)return ['sun','맑음'];if(code===1)return ['partly','대체로 맑음'];if(code===2)return ['partly','구름 조금'];if(code===3)return ['cloud','흐림'];if(code===45||code===48)return ['fog','안개'];if(code>=51&&code<=57)return ['drizzle','이슬비'];if(code>=61&&code<=67)return ['rain',code>=65?'강한 비':'비'];if(code>=71&&code<=77)return ['snow','눈'];if(code>=80&&code<=82)return ['drizzle','소나기'];if(code>=85&&code<=86)return ['snow','눈 소나기'];if(code>=95)return ['storm','뇌우'];return ['cloud','날씨'];}
function hourText(iso){var d=new Date(iso);return String(d.getHours()).padStart(2,'0')+'시';}
function currentIndex(data){var times=data&&data.hourly&&data.hourly.time||[];if(!times.length)return 0;var now=Date.now(),best=0,dist=Infinity;times.forEach(function(t,i){var dd=Math.abs(new Date(t).getTime()-now);if(dd<dist){dist=dd;best=i;}});return best;}
function forecastSlice(data,hours){var i=currentIndex(data),out=[];for(var n=i;n<Math.min((data.hourly.time||[]).length,i+hours);n++)out.push({time:data.hourly.time[n],temp:Number(data.hourly.temperature_2m[n]),prob:Number(data.hourly.precipitation_probability[n]||0),precip:Number(data.hourly.precipitation[n]||0),rain:Number(data.hourly.rain[n]||0),showers:Number(data.hourly.showers[n]||0),code:Number(data.hourly.weather_code[n])});return out;}
function umbrellaInfo(data){var arr=forecastSlice(data,8),rainHours=arr.filter(function(x){return x.rain>0.05;}),sum=rainHours.reduce(function(a,x){return a+x.rain;},0),maxRain=rainHours.reduce(function(a,x){return Math.max(a,x.rain);},0),maxProb=rainHours.reduce(function(a,x){return Math.max(a,x.prob);},0);var heavyCode=arr.some(function(x){return x.code===63||x.code===65||x.code===66||x.code===67;});var should=rainHours.length>0&&maxProb>=70&&(sum>=2||maxRain>=1||heavyCode);if(!should)return {show:false,sum:sum,maxRain:maxRain,maxProb:maxProb};var first=rainHours[0],last=rainHours[rainHours.length-1];return {show:true,sum:sum,maxRain:maxRain,maxProb:maxProb,from:hourText(first.time),to:hourText(last.time)};}
function currentRaining(data){
  var c=data&&data.current||{},code=Number(c.weather_code);
  var amount=Number(c.rain||0)+Number(c.showers||0);
  return amount>0.01||(code>=51&&code<=67)||(code>=80&&code<=82)||(code>=95&&code<=99);
}
function rainPeek(data){var arr=forecastSlice(data,12),today=new Date();return arr.find(function(x){var d=new Date(x.time),wet=x.precip>0.05||x.rain>0.05||x.showers>0.05||x.code>=51;return d.getFullYear()===today.getFullYear()&&d.getMonth()===today.getMonth()&&d.getDate()===today.getDate()&&x.prob>=60&&wet;})||null;}
function apiURL(lat,lon){var q=new URLSearchParams({latitude:String(lat),longitude:String(lon),current:'temperature_2m,weather_code,is_day,precipitation,rain,showers',hourly:'temperature_2m,precipitation_probability,precipitation,rain,showers,weather_code',forecast_days:'2',timezone:'auto',cell_selection:'land'});return 'https://api.open-meteo.com/v1/forecast?'+q.toString();}
function fetchWeather(lat,lon,accuracy){CACHE.pending=true;CACHE.error='';return fetch(apiURL(lat,lon),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('weather '+r.status);return r.json();}).then(function(data){if(!data||!data.current||!data.hourly)throw new Error('bad weather data');CACHE.data=data;CACHE.at=Date.now();CACHE.lat=lat;CACHE.lon=lon;CACHE.accuracy=accuracy;CACHE.pending=false;CACHE.error='';renderInline();return data;}).catch(function(e){CACHE.pending=false;CACHE.error='날씨를 불러오지 못했어요';renderInline();throw e;});}
function locate(force){if(!enabled())return Promise.resolve(null);if(CACHE.pending)return Promise.resolve(CACHE.data);var now=Date.now();if(!force&&CACHE.data&&now-CACHE.at<REFRESH_MS){renderInline();return Promise.resolve(CACHE.data);}if(!force&&CACHE.lastAttempt&&now-CACHE.lastAttempt<REFRESH_MS){renderInline();return Promise.resolve(CACHE.data);}if(!navigator.geolocation){CACHE.error='현재 위치를 사용할 수 없는 브라우저예요';renderInline();return Promise.resolve(null);}CACHE.pending=true;CACHE.lastAttempt=Date.now();renderInline();return new Promise(function(resolve){navigator.geolocation.getCurrentPosition(function(pos){var a=Number(pos.coords.accuracy||99999);CACHE.permission='granted';CACHE.pending=false;if(a>MAX_ACCURACY_M){CACHE.error='위치가 너무 넓게 잡혀서 날씨를 표시하지 않았어요';CACHE.accuracy=a;renderInline();resolve(null);return;}fetchWeather(pos.coords.latitude,pos.coords.longitude,a).then(resolve).catch(function(){resolve(null);});},function(err){CACHE.pending=false;CACHE.permission=err&&err.code===1?'denied':'error';CACHE.error=err&&err.code===1?'위치 권한이 꺼져 있어요':'현재 위치를 확인하지 못했어요';renderInline();resolve(null);},{enableHighAccuracy:true,timeout:10000,maximumAge:10*60*1000});});}
function inlineHTML(){if(!enabled())return '';if(CACHE.pending&&!CACHE.data)return '<button class="wx-title-weather connect" data-wx-act="details">'+wxIcon('location')+'<span>위치 확인 중</span></button>';if(CACHE.data){var m=codeMeta(CACHE.data.current.weather_code),temp=Math.round(Number(CACHE.data.current.temperature_2m)),r=rainPeek(CACHE.data),nowRain=currentRaining(CACHE.data);if(nowRain)return '<button class="wx-title-weather rain" data-wx-act="details">'+wxIcon('rain')+'<span>'+temp+'° 비</span></button>';if(r)return '<button class="wx-title-weather rain" data-wx-act="details">'+wxIcon('rain')+'<span>'+esc(hourText(r.time))+' 비 '+Math.round(r.prob)+'%</span></button>';return '<button class="wx-title-weather" data-wx-act="details">'+wxIcon(m[0])+'<span>'+temp+'° '+esc(m[1])+'</span></button>';}return '<button class="wx-title-weather connect" data-wx-act="refresh">'+wxIcon('location')+'<span>위치 연결</span></button>';}
function renderInline(){var u=ui();document.querySelectorAll('.wx-inline,.wx-title-weather').forEach(function(x){x.remove();});if(!u||u.tab!=='day'||!enabled())return;var sub=document.querySelector('#top .ttl small');if(!sub)return;var chip=document.createElement('span');chip.innerHTML=inlineHTML();var btn=chip.firstElementChild;if(!btn)return;var txt=sub.textContent||'';if(/^오늘(?:\s*·|$)/.test(txt)){var first=document.createTextNode('오늘');sub.textContent='';sub.appendChild(first);sub.appendChild(btn);var rest=txt.replace(/^오늘\s*/, '');if(rest)sub.appendChild(document.createTextNode(' '+rest));}else{sub.appendChild(btn);}}
function settingsHTML(){var on=enabled(),status='앱을 열거나 다시 돌아올 때 현재 위치로 날씨를 갱신해요.';if(CACHE.accuracy&&isFinite(CACHE.accuracy))status+=' · 최근 위치 정확도 약 '+(CACHE.accuracy<1000?Math.round(CACHE.accuracy)+'m':(CACHE.accuracy/1000).toFixed(1)+'km');if(CACHE.error)status=CACHE.error;return '<section class="card wx-settings"><div class="card-h"><h3>현재 위치 날씨</h3></div><div class="setrow"><span>일간 화면에 자동 표시<small>기온·날씨와 필요한 날만 우산 알림을 보여줘요</small></span><button class="tbtn'+(on?' on':'')+'" data-wx-act="toggle">'+(on?'켜짐':'꺼짐')+'</button></div><div class="setrow"><span>위치 연결 · 새로고침<small>정확도가 너무 낮으면 날씨를 억지로 표시하지 않아요</small></span><button class="tbtn" data-wx-act="refresh">'+wxIcon('location','wx-btn-ico')+'<span>연결</span></button></div><p class="wx-status '+(CACHE.error?'bad':'')+'">'+esc(status)+'</p><p class="wx-note">위치 좌표는 플래너 데이터에 저장하거나 계정에 동기화하지 않고, 현재 날씨를 조회할 때만 사용해요. 우산 알림은 앞으로 약 8시간 안에 강수확률이 높고 실제 비 예보량도 충분할 때만 보수적으로 표시해요.</p></section>';}
function injectSettings(){var u=ui();if(!u||u.tab!=='settings'||u.settingsPage!=='life')return;var main=document.getElementById('main');if(!main||main.querySelector('.wx-settings'))return;main.insertAdjacentHTML('beforeend',settingsHTML());}
function details(){if(!CACHE.data){B.openModal('<h3>현재 위치 날씨</h3><p class="hint">현재 위치와 시간대별 예보를 불러오고 있어요.</p><div class="acts"><button class="b-save" data-wx-act="refresh">'+wxIcon('refresh','wx-btn-ico')+'<span>다시 불러오기</span></button></div>');locate(true).then(function(d){if(d&&CACHE.data)details();});return;}var data=CACHE.data,m=codeMeta(data.current.weather_code),nowRain=currentRaining(data),u=umbrellaInfo(data),arr=forecastSlice(data,10);var hourly=arr.map(function(x){var mm=codeMeta(x.code);return '<div class="wx-hour"><b>'+esc(hourText(x.time))+'</b>'+wxIcon(mm[0],'wx-hour-ico')+'<small>'+Math.round(x.temp)+'°</small><small>비 '+Math.round(x.prob)+'%</small></div>';}).join('');var rain=u.show?'<div class="wx-raincard"><b>'+wxIcon('umbrella','wx-btn-ico')+'<span>우산 챙기세용</span></b><small>'+esc(u.from)+'~'+esc(u.to)+' 비 예상 · 최대 '+Math.round(u.maxProb)+'% · 약 '+u.sum.toFixed(1)+'mm</small></div>':'<div class="note">우산 알림 기준에 해당하는 강한 비 예보는 없어요.</div>';var acc=CACHE.accuracy&&isFinite(CACHE.accuracy)?(CACHE.accuracy<1000?Math.round(CACHE.accuracy)+'m':(CACHE.accuracy/1000).toFixed(1)+'km'):'알 수 없음';B.openModal('<h3>오늘 날씨</h3><div class="wx-hero"><div class="wx-big">'+wxIcon(m[0],'wx-big-ico')+'</div><div class="wx-nowcopy"><div class="wx-temp">'+Math.round(Number(data.current.temperature_2m))+'°</div><div class="wx-desc">'+esc(nowRain?'비':m[1])+' · 현재 위치 정확도 약 '+esc(acc)+'</div></div></div>'+rain+'<div class="wx-hourly">'+hourly+'</div><p class="wx-note">예보는 Open-Meteo의 최신 모델 데이터를 사용해요. 소나기 가능성만 있는 경우에는 우산 알림을 띄우지 않도록 보수적으로 설정했어요.</p><div class="wx-actions"><button data-wx-act="refresh">'+wxIcon('refresh','wx-btn-ico')+'<span>위치·날씨 새로고침</span></button><button class="pri" data-wx-act="close">닫기</button></div>');}
function afterRender(){ensureDefault();addStyles();renderInline();injectSettings();if(enabled()){var u=ui();if(u&&u.tab==='day')locate(false);}}
function click(e){var a=e.target.closest&&e.target.closest('[data-wx-act]');if(!a)return;var act=a.dataset.wxAct;if(act==='details'){details();return;}if(act==='refresh'){locate(true).then(function(){if(document.getElementById('modal')&&document.getElementById('modal').classList.contains('open'))details();});return;}if(act==='toggle'){var s=state();if(!s||!s.settings)return;s.settings.weatherOn=!enabled();B.save();B.render(false);if(s.settings.weatherOn)locate(true);return;}if(act==='close'){B.closeModal();return;}}
document.addEventListener('click',click);
document.addEventListener('visibilitychange',function(){if(!document.hidden&&enabled()&&Date.now()-CACHE.at>REFRESH_MS)locate(true);});
window.addEventListener('online',function(){if(enabled()&&Date.now()-CACHE.at>REFRESH_MS)locate(true);});
window.PLANON_WEATHER={afterRender:afterRender,refresh:function(){return locate(true);},details:details,renderInline:renderInline,data:function(){return CACHE.data;},timezone:function(){return CACHE.data&&CACHE.data.timezone?CACHE.data.timezone:null;}};
afterRender();
})();
