(function(){
'use strict';
function B(){return window.PLANON_UX_BRIDGE;} function E(){return window.PLANON_MARKET_THEME;} function C(){return window.PLANON_MARKET_CATALOG||{products:[]};}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function uid(){try{return crypto.randomUUID();}catch(e){return 'pk-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}}
function today(){return B().todayKey();} function iso(x){var m=String(x||'').match(/\d{4}-\d{2}-\d{2}/);return m?m[0]:'';}
var DEF={
 classNotes:{title:'수업 · 강의 노트',sub:'강의가 끝나면 복습·시험·과제로 바로 연결',kind:'lecture',parent:'학생 학업',fields:[['수업명','text'],['수업일','date'],['오늘 핵심 3줄','textarea'],['교수님 강조','textarea'],['질문 · 모르는 점','textarea'],['시험 범위 태그','text'],['과제 · 다음 준비','textarea'],['복습 상태','select',['미복습','1일 복습','3일 복습','7일 복습','완료']]]},
 assignment:{title:'과제 완성판',sub:'마감까지 남은 단계를 체크하는 제출 보드',kind:'steps',parent:'학생 학업',fields:[['과제명','text'],['마감일','date'],['자료조사','check'],['초안','check'],['수정 · 검토','check'],['제출 전 확인','check']]},
 teamProject:{title:'팀플 작업판',sub:'역할·회의·내 액션을 한 흐름으로',kind:'meeting',parent:'학생 학업',fields:[['팀플명','text'],['다음 회의','date'],['이번 회의 주제','textarea'],['결정사항','textarea'],['내 담당','textarea'],['담당 기한','date']]},
 jobPrep:{title:'지원 파이프라인',sub:'지원서를 단계별로 넘기는 취준 보드',kind:'pipeline',parent:'학생 커리어',stages:['관심','서류 준비','지원 완료','면접','결과'],fields:[['기업 · 기관','text'],['직무','text'],['서류 마감','date'],['현재 단계','select',['관심','서류 준비','지원 완료','면접','결과']],['다음 준비','textarea'],['면접 · 결과 메모','textarea']]},
 examSemester:{title:'학기 시험 대시보드',sub:'과목별 시험일·범위·복습 단계를 한눈에',kind:'exam',parent:'시험',fields:[['과목','text'],['시험일','date'],['시험 범위','textarea'],['진도 %','number'],['복습 단계','select',['개념','문제풀이','오답','최종복습','완료']],['목표','text']]},
 examCram:{title:'D-day 구조대',sub:'남은 시간에 반드시 할 것부터',kind:'cram',parent:'시험',fields:[['시험 · 과목','text'],['시험일','date'],['반드시 끝낼 것','textarea'],['시간 남으면','textarea'],['미뤄도 되는 것','textarea'],['오늘 확보 시간(분)','number']]},
 examLong:{title:'장기 수험 코어',sub:'주간 목표·회독·누적 진도를 관리하는 기본 장기수험팩',kind:'examLong',parent:'장기 수험',fields:[['과목','text'],['목표일','date'],['이번 주 목표','textarea'],['현재 회독','number'],['누적 진도 %','number'],['모의시험','text'],['다음 주 보완','textarea']]},
 entranceExam:{title:'입시 · 재수 확장',sub:'장기 수험 코어에 순공·실전 시간표·오답을 더한 입시 특화',kind:'entrance',parent:'장기 수험 확장',fields:[['시험명 · 목표','text'],['시험일','date'],['오늘 순공 목표(분)','number'],['과목별 공부 비율','textarea'],['실전 시간표 연습','textarea'],['모의고사 점수','text'],['오답 · 취약유형','textarea'],['내일 보정 플랜','textarea']]},
 certificate:{title:'자격증 · 어학 영역판',sub:'영역별 회독과 기출 점수를 쌓아요',kind:'exam',parent:'시험',fields:[['시험명','text'],['시험일','date'],['영역','text'],['회독','number'],['기출 · 모의 점수','text'],['약한 부분','textarea'],['다음 공부','textarea']]},
 meetingNotes:{title:'회의 → 실행',sub:'회의 내용보다 결정과 후속 행동이 남는 회의록',kind:'meeting',parent:'업무',fields:[['회의명','text'],['회의일','date'],['참석자','text'],['안건 · 목적','textarea'],['핵심 논의','textarea'],['결정사항','textarea'],['액션아이템','textarea'],['담당자','text'],['기한','date']]},
 workday:{title:'오늘 업무판',sub:'실행·대기·이월을 분리한 데일리 워크보드',kind:'work',parent:'업무',fields:[['업무명','text'],['마감','date'],['우선순위','select',['높음','보통','낮음']],['현재 상태','select',['할 일','진행 중','대기','완료']],['대기 · 확인할 것','textarea'],['내일로 넘길 것','textarea']]},
 project:{title:'프로젝트 보드',sub:'마일스톤·리스크·다음 액션 중심',kind:'project',parent:'업무',fields:[['프로젝트명','text'],['목표일','date'],['목표','textarea'],['마일스톤','textarea'],['현재 작업','textarea'],['리스크 · 막힘','textarea'],['다음 액션','textarea']]},
 startup:{title:'창업 실험 보드',sub:'아이디어가 아니라 가설→근거→실험→결과를 쌓아요',kind:'startup',parent:'창업',fields:[['아이템 · 프로젝트','text'],['다음 검증일','date'],['문제 정의','textarea'],['타깃 고객','textarea'],['검증할 가설','textarea'],['고객 인터뷰 근거','textarea'],['이번 실험','textarea'],['실험 결과','textarea'],['MVP 다음 액션','textarea'],['핵심 지표','text']]},
 businessDocs:{title:'사업계획서 재료함',sub:'지원서 문항을 평소 근거 카드로 축적',kind:'docs',parent:'창업',fields:[['문서 · 지원사업명','text'],['마감일','date'],['문제 · 필요성','textarea'],['고객 · 시장 근거','textarea'],['솔루션','textarea'],['경쟁 · 차별점','textarea'],['수익모델','textarea'],['시장검증 근거','textarea'],['실행계획','textarea'],['팀 · 역할','textarea'],['예산 · 자원','textarea'],['성과지표','textarea']]},
 content:{title:'콘텐츠 파이프라인 CORE',sub:'아이디어→제작→업로드 상태만 빠르게 관리',kind:'pipeline',parent:'크리에이터',stages:['아이디어','대본','촬영','편집','업로드'],fields:[['콘텐츠명','text'],['업로드일','date'],['현재 단계','select',['아이디어','대본','촬영','편집','업로드']],['훅 · 핵심','textarea'],['다음 작업','textarea']]},
 creatorScript:{title:'스크립트 제작 확장',sub:'콘텐츠 CORE에 씬·대사·촬영 체크를 더한 제작 특화',kind:'pipeline',parent:'크리에이터 확장',stages:['아이디어','대본','촬영','편집','업로드'],fields:[['콘텐츠명 · 훅','text'],['업로드일','date'],['현재 단계','select',['아이디어','대본','촬영','편집','업로드']],['씬별 구성','textarea'],['대사 · 자막','textarea'],['촬영 준비물','textarea'],['촬영일','date'],['편집 체크','textarea'],['성과 메모','textarea']]},
 freelance:{title:'N잡 · 프리랜서 보드',sub:'클라이언트·시간·정산·미수금을 분리',kind:'moneywork',parent:'업무 확장',fields:[['프로젝트 · 부캐','text'],['마감','date'],['클라이언트','text'],['예상 작업시간','number'],['단가 · 금액','number'],['정산일','date'],['현재 작업','textarea'],['미수금 · 확인','textarea'],['다음 액션','textarea']]},
 habitChallenge:{title:'갓생 챌린지',sub:'스트릭보다 실패 이유와 다음 조정까지',kind:'habit',parent:'라이프',fields:[['루틴 · 챌린지','text'],['종료일','date'],['이번 주 목표','text'],['오늘 인증','check'],['연속 달성','number'],['실패 이유','textarea'],['다음 조정','textarea']]},
 independent:{title:'자취 생활판',sub:'빨래·청소·분리수거·납부·유통기한을 마지막으로 한 날부터 관리',kind:'life',parent:'라이프',fields:[['항목','text'],['마지막으로 한 날 · 기준일','date'],['종류','select',['빨래','침구 세탁','청소','화장실 청소','분리수거','식재료','공과금','월세·관리비','장보기','기타']],['다음 할 일 · 남은 것','text'],['장보기 · 준비','textarea'],['반복 주기','text']]},
 budget:{title:'머니 플래너',sub:'예산에서 실제 사용액을 빼며 남은 금액을 봐요',kind:'budget',parent:'머니',fields:[['예산 항목','text'],['기준일','date'],['예산 · 목표 금액','number'],['사용 · 납부 금액','number'],['고정지출','check'],['메모','textarea']]},
 fitness:{title:'운동 · 식단 로그',sub:'운동 수행과 식사·물 기록을 하루 단위로',kind:'fitness',parent:'라이프',fields:[['날짜 · 목표','text'],['기록일','date'],['오늘 운동','textarea'],['세트 · 시간','text'],['식사 기록','textarea'],['물 체크','text'],['이번 주 달성 %','number'],['다음 운동','textarea']]},
 travel:{title:'여행 타임라인',sub:'DAY별 동선·예약·준비물·정산을 한 여행 안에서',kind:'travel',parent:'여행',fields:[['여행명 · 여행지','text'],['출발일','date'],['귀국 · 종료일','date'],['DAY별 동선','textarea'],['예약 · 티켓','textarea'],['준비물 체크리스트','textarea'],['동행인 · 1/N 정산','textarea'],['다녀온 곳 · 한줄평','textarea'],['추억카드 메모','textarea']]},
 routine:{title:'루틴 리셋',sub:'이번 주 유지할 루틴만 간단하게',kind:'habit',parent:'라이프',fields:[['루틴명','text'],['시작일','date'],['이번 주 목표','text'],['오늘 체크','check'],['막힌 이유','textarea'],['다음 조정','textarea']]},
 couple:{title:'커플 플래너',sub:'기념일·약속·준비·추억을 한 카드로',kind:'couple',parent:'라이프',fields:[['약속 · 기념일','text'],['날짜','date'],['장소','text'],['함께할 것','textarea'],['준비물','textarea'],['추억 메모','textarea']]},
 fandom:{title:'덕질 캘린더',sub:'컴백·티켓팅·예판·배송을 이벤트별로',kind:'fandom',parent:'팬덤',fields:[['최애 · 작품','text'],['일정명','text'],['날짜','date'],['종류','select',['컴백','공연','티켓팅','예판','팝업','방송','생일카페','배송','기타']],['티켓팅 준비','textarea'],['굿즈 · 예판 · 배송','textarea'],['방문 일정','textarea'],['기록 · 추억','textarea']]},
 lifeAdmin:{title:'생활 행정 보드',sub:'예약·반납·갱신처럼 생활 속 마감 업무를 끝까지',kind:'lifeAdmin',parent:'머니 · 생활',fields:[['할 일 · 예약','text'],['기한 · 예약일','date'],['종류','select',['병원·미용','은행·행정','택배·반납','구독·갱신','계약·보증금','기타']],['현재 상태','select',['해야 함','예약함','준비 중','완료']],['준비물 · 가져갈 것','textarea'],['예약번호 · 메모','textarea'],['다음 갱신일','date']]},
 portfolio:{title:'포트폴리오 빌더',sub:'프로젝트 경험을 결과와 근거가 남는 포트폴리오 카드로',kind:'portfolio',parent:'학생 커리어',fields:[['프로젝트명','text'],['마감 · 공개일','date'],['문제 · 목표','textarea'],['내 역할 · 한 일','textarea'],['결과','textarea'],['수치 · 근거','textarea'],['이미지 · 링크 메모','textarea'],['회고 · 배운 점','textarea'],['공개 상태','select',['정리 중','검토 필요','공개 준비','완료']]]},
 eventOps:{title:'행사 · 운영 보드',sub:'동아리·스터디·축제·공모전을 준비부터 당일까지',kind:'eventOps',parent:'직장 · 프로젝트',fields:[['행사 · 프로젝트명','text'],['행사일 · 마감','date'],['목표 · 성공 기준','textarea'],['마일스톤','textarea'],['역할 · 담당','textarea'],['준비물 · 체크','textarea'],['회의 결정사항','textarea'],['당일 운영 체크','textarea'],['리스크 · 비상안','textarea'],['회고 · 다음 개선','textarea']]},
 petCare:{title:'반려동물 케어',sub:'접종·복약·용품 교체를 다음 체크일까지',kind:'pet',parent:'반려생활',fields:[['반려동물 이름','text'],['다음 체크일','date'],['건강 일정','textarea'],['사료 · 모래 · 용품 교체','textarea'],['오늘 식사 · 간식','textarea'],['산책 · 놀이','textarea'],['컨디션 · 배변 메모','textarea']]}
};
function actives(){var m=E&&E()&&E().state&&E().state();if(!m)return [];var ids=(m.activeFunctionalPacks||[]).slice(),last=m.active&&m.active.functionalPack;if(last&&ids.indexOf(last)<0)ids.push(last);return ids.map(function(id){return (C().products||[]).find(function(x){return x.id===id;});}).filter(function(p){return p&&p.payload&&DEF[p.payload.packKey];});}
function store(){var s=B().state();s.settings.planonPacks=s.settings.planonPacks||{entries:{},homePrefs:{}};s.settings.planonPacks.entries=s.settings.planonPacks.entries||{};s.settings.planonPacks.homePrefs=s.settings.planonPacks.homePrefs||{};return s.settings.planonPacks;}
function rows(k){return store().entries[k]||(store().entries[k]=[]);} function val(r,i){return r&&r.values?r.values[i]||'':'';}
function pct(r,d){if(d.kind==='steps'){var xs=[2,3,4,5];return Math.round(xs.filter(function(i){return val(r,i)==='1';}).length/xs.length*100);} var vals=(r.values||[]).slice(2),n=vals.length,done=vals.filter(function(x){return String(x||'').trim();}).length;return n?Math.round(done/n*100):0;}
function daysUntil(s){var d=iso(s);if(!d)return 9999;return Math.ceil((new Date(d+'T12:00:00')-new Date(today()+'T12:00:00'))/86400000);}
function urgency(p){var k=p.payload.packKey,d=DEF[k],rs=rows(k),score=10;rs.forEach(function(r){d.fields.forEach(function(f,i){if(f[1]==='date'){var n=daysUntil(val(r,i));if(n<0)return;if(n===0)score=Math.max(score,120);else if(n<=1)score=Math.max(score,110);else if(n<=3)score=Math.max(score,95);else if(n<=7)score=Math.max(score,75);}});});if(k==='meetingNotes')score+=5;if(k==='examCram')score+=8;return score;}
function badge(r,d){if(d.kind==='pipeline')return val(r,2)||'아이디어';if(d.kind==='exam'||d.kind==='entrance'||d.kind==='examLong'||d.kind==='cram'){var n=daysUntil(val(r,1));return n<9999?(n<0?'종료':n===0?'D-DAY':'D-'+n):pct(r,d)+'%';}if(d.kind==='steps')return pct(r,d)+'%';if(d.kind==='budget'){var left=(Number(val(r,2))||0)-(Number(val(r,3))||0);return '잔액 '+left.toLocaleString();}return pct(r,d)+'%';}
function visual(r,d){if(d.kind==='pipeline'){var st=d.stages||[],cur=val(r,2),ix=Math.max(0,st.indexOf(cur));return '<div class="pack-pipeline">'+st.map(function(x,i){return '<span class="'+(i<ix?'done':i===ix?'now':'')+'">'+esc(x)+'</span>';}).join('')+'</div>';}
 if(d.kind==='steps'){return '<div class="pack-stepbar"><i style="width:'+pct(r,d)+'%"></i></div>';}
 if(d.kind==='exam'||d.kind==='entrance'||d.kind==='examLong'){var prog=Math.max(0,Math.min(100,Number(val(r,d.kind==='exam'?3:d.kind==='examLong'?4:0))||0));return prog?'<div class="pack-stepbar"><i style="width:'+prog+'%"></i></div>':'';}
 if(d.kind==='budget'){var a=Number(val(r,2))||0,b=Number(val(r,3))||0,p=a?Math.min(100,Math.round(b/a*100)):0;return '<div class="pack-stepbar budget"><i style="width:'+p+'%"></i></div>';}
 return '';}
function emptyCopy(k,d){var m={classNotes:['첫 수업을 정리해볼까요?','핵심·질문·복습까지 한 번에 이어져요'],assignment:['첫 과제를 단계로 나눠보세요','마감 전 제출 체크포인트가 보여요'],meetingNotes:['첫 회의를 기록해볼까요?','결정사항이 다음 할 일로 이어져요'],startup:['검증할 첫 가설을 적어보세요','아이디어보다 실험과 근거를 쌓아요'],travel:['첫 여행을 만들어보세요','DAY 동선·예약·준비·정산을 한곳에 모아요'],examSemester:['첫 시험을 등록해보세요','D-day와 진도를 한눈에 관리해요'],examCram:['남은 시간을 구조해볼까요?','반드시 할 것부터 우선순위를 잡아요'],jobPrep:['첫 지원을 파이프라인에 올려보세요','서류부터 결과까지 흐름을 놓치지 않아요'],content:['첫 콘텐츠를 시작해보세요','아이디어가 업로드까지 이동해요'],creatorScript:['첫 대본을 만들어보세요','씬·촬영·편집을 제작 흐름으로 관리해요'],budget:['첫 예산을 만들어보세요','쓴 만큼 남은 금액이 바로 보여요'],petCare:['첫 케어 일정을 등록해보세요','접종·복약·용품 교체일을 놓치지 않아요'],fandom:['첫 최애 일정을 등록해보세요','컴백·티켓팅·예판을 한 캘린더로 모아요']};return m[k]||['첫 기록을 만들어보세요',d.sub];}
function heroMetric(k,r,d){if(!r)return '';if(k==='meetingNotes')return '<strong class="pack-metric">'+esc(val(r,1)||'회의일 미정')+'</strong><span>다음 액션 · '+esc(val(r,6)||'아직 없음')+'</span>';if(k==='travel')return '<strong class="pack-metric">'+esc(val(r,1)||'출발일 미정')+'</strong><span>'+esc(val(r,3)||'DAY 동선을 채워보세요')+'</span>';if(k==='startup')return '<strong class="pack-metric">NEXT EXPERIMENT</strong><span>'+esc(val(r,6)||val(r,8)||'검증 실험을 정해보세요')+'</span>';if(k==='budget'){var a=Number(val(r,2))||0,b=Number(val(r,3))||0;return '<strong class="pack-metric">'+Math.max(0,a-b).toLocaleString()+' 남음</strong><span>예산 '+a.toLocaleString()+' · 사용 '+b.toLocaleString()+'</span>';}if(k.indexOf('exam')===0||k==='entranceExam'||k==='certificate'){return '<strong class="pack-metric">'+esc(badge(r,d))+'</strong><span>'+esc(val(r,0)||'시험')+' · '+esc(val(r,4)||val(r,2)||'진도를 기록해보세요')+'</span>';}if(k==='classNotes')return '<strong class="pack-metric">'+esc(val(r,0)||'오늘 수업')+'</strong><span>복습 · '+esc(val(r,7)||'미복습')+'</span>';return '';}
function resultStrip(k,r,d){if(!r)return '';var t='';if(d.kind==='steps')t='제출 준비 '+pct(r,d)+'%';else if(d.kind==='pipeline')t='현재 단계 · '+(val(r,2)||'아이디어');else if(d.kind==='budget'){var a=Number(val(r,2))||0,b=Number(val(r,3))||0;t='남은 예산 · '+Math.max(0,a-b).toLocaleString();}else if(k==='classNotes')t='복습 상태 · '+(val(r,7)||'미복습');else if(k==='startup')t='다음 액션 · '+(val(r,8)||'아직 정하지 않음');else if(k==='travel')t='출발 · '+(val(r,1)||'날짜 미정');else if(k==='meetingNotes')t='후속 액션 · '+(val(r,6)||'아직 없음');else if(k==='lifeAdmin')t='현재 상태 · '+(val(r,3)||'해야 함');else if(k==='portfolio')t='포트폴리오 · '+(val(r,8)||'정리 중');else if(k==='eventOps'){var n=daysUntil(val(r,1));t=n===0?'오늘 운영':n<9999&&n>0?'행사 D-'+n:'운영 준비';}else t=badge(r,d);return '<div class="pack-result-strip"><small>현재 결과</small><b>'+esc(t)+'</b></div>';}
function oneCard(p){var k=p.payload.packKey,d=DEF[k],all=rows(k).slice().sort(function(a,b){return Number(b.updatedAt||0)-Number(a.updatedAt||0);}),latest=all.slice(0,3),top=latest[0],ec=emptyCopy(k,d);return '<section class="pack-home-card pack-kind-'+d.kind+' pack-card-'+k+'" data-pack-key="'+k+'"><div class="pack-home-head"><span><small>'+esc(d.parent)+' · 설치된 기능팩</small><b>'+esc(d.title)+'</b><em>'+esc(d.sub)+'</em></span><button data-pack-add="'+k+'">+ 작성</button></div>'+heroMetric(k,top,d)+'<div class="pack-home-list">'+(latest.length?latest.map(function(r){return '<button class="pack-home-row" data-pack-edit="'+esc(r.id)+'" data-pack-key="'+k+'"><span><b>'+esc(val(r,0)||'새 기록')+'</b><small>'+esc(val(r,1)||d.sub)+'</small>'+visual(r,d)+'</span><i>'+esc(badge(r,d))+'</i></button>';}).join(''):'<button class="pack-home-empty pack-empty-'+d.kind+'" data-pack-add="'+k+'"><span><b>'+esc(ec[0])+'</b><small>'+esc(ec[1])+'</small></span><i>시작하기 ›</i></button>')+'</div></section>';}

function synergy(ps){var ks=ps.map(function(p){return p.payload.packKey;}),m=[];if(ks.includes('fandom')&&ks.includes('travel'))m.push('덕질 × 여행 · 공연 원정을 여행 타임라인으로 연결');if((ks.includes('creatorScript')||ks.includes('content'))&&ks.includes('meetingNotes'))m.push('크리에이터 × 회의 · 결정사항을 다음 제작 작업으로 연결');if(ks.includes('classNotes')&&(ks.includes('examSemester')||ks.includes('entranceExam')))m.push('수업노트 × 시험 · 시험범위와 복습 할 일을 연결');if(ks.includes('startup')&&ks.includes('meetingNotes'))m.push('창업 × 회의 · 결정사항을 다음 검증 실험으로 연결');if(ks.includes('portfolio')&&(ks.includes('project')||ks.includes('startup')))m.push('프로젝트 × 포트폴리오 · 실행 결과와 근거를 포트폴리오 카드로 축적');if(ks.includes('eventOps')&&ks.includes('meetingNotes'))m.push('행사 운영 × 회의 · 결정사항을 당일 운영 체크로 연결');return m.length?'<div class="pack-synergy"><small>PACK SYNERGY</small>'+m.slice(0,2).map(function(x){return '<b>'+esc(x)+'</b>';}).join('')+'</div>':'';}
function cardHTML(){var ps=actives().slice().sort(function(a,b){return urgency(b)-urgency(a);}),open=store().homePrefs.showAll===true,shown=open?ps:ps.slice(0,4),more=Math.max(0,ps.length-shown.length);return synergy(ps)+shown.map(oneCard).join('')+(ps.length>4?'<button class="pack-show-more" data-pack-toggle-all>'+ (open?'오늘 중요한 팩만 보기':'설치된 팩 '+more+'개 더 보기') +' <span>›</span></button>':'');}
function inject(){var h=document.querySelector('.home.home-clean');if(!h)return;h.querySelectorAll('.pack-home-card,.pack-synergy').forEach(function(x){x.remove();});var html=cardHTML();if(!html)return;var q=document.createElement('div');q.innerHTML=html;Array.from(q.children).forEach(function(x){h.appendChild(x);});}
function fieldHTML(f,i,v){var name=f[0],type=f[1],opts=f[2]||[];if(type==='textarea')return '<label class="pack-field pack-wide"><span>'+esc(name)+'</span><textarea data-pack-field="'+i+'" placeholder="'+esc(name)+'">'+esc(v)+'</textarea></label>';if(type==='select')return '<label class="pack-field"><span>'+esc(name)+'</span><select data-pack-field="'+i+'">'+opts.map(function(o){return '<option '+(v===o?'selected':'')+'>'+esc(o)+'</option>';}).join('')+'</select></label>';if(type==='check')return '<label class="pack-check"><input type="checkbox" data-pack-field="'+i+'" '+(v==='1'?'checked':'')+'><span>'+esc(name)+'</span></label>';return '<label class="pack-field"><span>'+esc(name)+'</span><input type="'+(type==='date'?'date':type==='number'?'number':'text')+'" data-pack-field="'+i+'" value="'+esc(v)+'" placeholder="'+esc(name)+'"></label>';}
function formSections(k,d,r){
 var map={
  classNotes:[['강의 정보',[0,1]],['오늘의 필기',[2,3,4]],['시험 · 과제 연결',[5,6]],['복습 루프',[7]]],
  assignment:[['과제 정보',[0,1]],['제출 체크포인트',[2,3,4,5]]],
  teamProject:[['팀플 헤더',[0,1]],['회의 스냅샷',[2,3]],['내 액션',[4,5]]],
  jobPrep:[['지원 카드',[0,1,2]],['지원 파이프라인',[3]],['다음 준비',[4,5]]],
  examSemester:[['시험 헤더',[0,1]],['범위 · 진도',[2,3]],['복습 단계',[4,5]]],
  examCram:[['D-DAY',[0,1,5]],['오늘 반드시',[2]],['여유가 생기면',[3]],['과감히 미루기',[4]]],
  examLong:[['목표 시험',[0,1]],['이번 주',[2,3,4]],['점검 · 보완',[5,6]]],
  entranceExam:[['목표 · D-DAY',[0,1]],['오늘 순공',[2,3]],['실전 훈련',[4,5]],['오답 → 내일 보정',[6,7]]],
  certificate:[['시험 정보',[0,1,2]],['회독 · 점수',[3,4]],['취약점 → 다음 공부',[5,6]]],
  meetingNotes:[['회의 헤더',[0,1,2]],['AGENDA',[3]],['DISCUSSION',[4]],['DECISION',[5]],['ACTION ITEM',[6,7,8]]],
  workday:[['오늘 업무',[0,1,2,3]],['대기 · 이월',[4,5]]],
  project:[['프로젝트 헤더',[0,1]],['목표 · 마일스톤',[2,3]],['NOW',[4]],['RISK',[5]],['NEXT ACTION',[6]]],
  startup:[['문제 · 고객',[0,2,3]],['HYPOTHESIS',[4]],['EVIDENCE',[5]],['EXPERIMENT',[1,6]],['RESULT',[7]],['NEXT MVP',[8,9]]],
  businessDocs:[['지원 문서',[0,1]],['WHY',[2,3]],['SOLUTION',[4,5]],['BUSINESS',[6,7]],['EXECUTION',[8,9,10,11]]],
  content:[['콘텐츠 카드',[0,1]],['PIPELINE',[2]],['HOOK',[3]],['NEXT',[4]]],
  creatorScript:[['콘텐츠 헤더',[0,1]],['PIPELINE',[2]],['SCRIPT · SCENE',[3,4]],['SHOOT',[5,6]],['EDIT · RESULT',[7,8]]],
  freelance:[['클라이언트 · 프로젝트',[0,1,2]],['시간 · 단가',[3,4]],['정산',[5,7]],['WORK',[6,8]]],
  habitChallenge:[['챌린지',[0,1,2]],['STREAK',[3,4]],['회고 · 조정',[5,6]]],
  independent:[['마지막 기록',[0,1,2]],['다음 생활일',[3,4]],['반복 주기',[5]]],
  budget:[['예산 카드',[0,1]],['BUDGET METER',[2,3]],['고정비 · 메모',[4,5]]],
  fitness:[['오늘 기록',[0,1]],['WORKOUT',[2,3]],['MEAL · WATER',[4,5]],['WEEK',[6,7]]],
  travel:[['TRIP',[0,1,2]],['DAY TIMELINE',[3]],['BOOKING',[4]],['PACKING',[5]],['SPLIT',[6]],['MEMORY',[7,8]]],
  routine:[['루틴',[0,1,2]],['TODAY',[3]],['RESET',[4,5]]],
  couple:[['DATE',[0,1,2]],['TOGETHER',[3,4]],['MEMORY',[5]]],
  fandom:[['FAVORITE',[0]],['EVENT',[1,2,3]],['TICKETING',[4]],['GOODS',[5]],['VISIT · MEMORY',[6,7]]],
  lifeAdmin:[['LIFE TASK',[0,1,2]],['STATUS',[3]],['PREP',[4,5]],['NEXT CYCLE',[6]]],
  portfolio:[['PROJECT',[0,1]],['PROBLEM → ROLE',[2,3]],['RESULT · EVIDENCE',[4,5]],['ASSET',[6]],['RETROSPECT',[7]],['PUBLISH',[8]]],
  eventOps:[['EVENT',[0,1]],['GOAL · MILESTONE',[2,3]],['PEOPLE',[4]],['PREP',[5]],['DECISION',[6]],['D-DAY OPS',[7,8]],['RETROSPECT',[9]]],
  petCare:[['PROFILE',[0,1]],['HEALTH',[2]],['SUPPLIES',[3]],['TODAY',[4,5,6]]]
 };
 var groups=map[k]||[['기록',d.fields.map(function(_,i){return i;})]];
 return groups.map(function(g,gi){return '<section class="pack-form-section pack-sec-'+gi+'"><div class="pack-section-head"><span>'+esc(g[0])+'</span></div><div class="pack-section-fields">'+g[1].map(function(i){return fieldHTML(d.fields[i],i,val(r,i));}).join('')+'</div></section>';}).join('');
}
function modal(k,id){var d=DEF[k];if(!d)return;var rs=rows(k),r=rs.find(function(x){return x.id===id;})||{id:'p'+Date.now().toString(36),values:[]};var body=formSections(k,d,r);B().openModal('<div class="pack-modal pack-form-'+d.kind+' pack-ui-'+k+'" data-pack-modal="'+k+'" data-pack-id="'+r.id+'"><div class="pack-modal-title"><small>'+esc(d.parent)+' · PLANON PACK</small><h3>'+esc(d.title)+'</h3><p>'+esc(d.sub)+'</p></div><div class="pack-special-form">'+body+'</div>'+resultStrip(k,r,d)+'<div class="pack-link-note"><b>기록과 플래너 연결은 따로 저장돼요.</b><span>메모만 남기려면 저장, 일정·할 일까지 만들려면 ‘저장하고 연결’을 선택하세요.</span></div><div class="acts pack-modal-actions">'+(id?'<button class="b-ghost" data-pack-delete="'+r.id+'">삭제</button>':'<button class="b-ghost" data-act="close">취소</button>')+'<button class="b-ghost" data-pack-save>저장</button><button class="b-save" data-pack-link>저장하고 연결</button></div></div>');}
function valuesFrom(m){var a=[];m.querySelectorAll('[data-pack-field]').forEach(function(x){a[Number(x.dataset.packField)]=x.type==='checkbox'?(x.checked?'1':''):x.value.trim();});return a;}
function connect(k,r){var d=DEF[k],v=r.values||[],made=[];function todo(text,due,course){if(!String(text||'').trim())return;B().addTodo('day',today(),String(text).trim(),'pack-'+uid(),iso(due)||null,course||'');made.push('할 일');}function event(title,date){date=iso(date);if(!title||!date)return;var s=B().state();s.allday.push({id:uid(),title:title,date:date,color:(s.settings&&s.settings.defColor)||'#faefdc',kind:'pack'});made.push('일정');}
 if(k==='classNotes'){todo(v[6],null,v[0]);if(v[5])todo('복습 · '+v[0]+' · '+v[5],null,v[0]);}
 else if(k==='assignment'){todo(v[0],v[1]);}
 else if(k==='teamProject'){todo(v[4],v[5]);event((v[0]||'팀플')+' 회의',v[1]);}
 else if(k==='meetingNotes'){todo(v[6],v[8]);event(v[0]||'회의',v[1]);}
 else if(k==='examSemester'||k==='certificate'||k==='entranceExam'||k==='examLong'||k==='examCram'){event((v[0]||'시험')+' 시험',v[1]);var idx=k==='examCram'?2:k==='entranceExam'?7:k==='examLong'?6:k==='certificate'?6:4;todo(v[idx],v[1],v[0]);}
 else if(k==='jobPrep'){event((v[0]||'지원')+' 마감',v[2]);todo(v[4],v[2]);}
 else if(k==='workday'){todo(v[0],v[1]);}
 else if(k==='project'){todo(v[6],v[1]);}
 else if(k==='startup'){todo(v[8]||v[6],v[1]);event((v[0]||'창업')+' 검증',v[1]);}
 else if(k==='businessDocs'){todo((v[0]||'사업계획서')+' 작성 마무리',v[1]);}
 else if(k==='content'||k==='creatorScript'){var ni=k==='content'?4:7;todo(v[ni]||('제작 · '+v[0]),v[1]);event((v[0]||'콘텐츠')+' 업로드',v[1]);}
 else if(k==='freelance'){todo(v[8]||v[0],v[1]);event((v[0]||'외주')+' 정산',v[5]);}
 else if(k==='travel'){event((v[0]||'여행')+' 출발',v[1]);todo(v[5],v[1]);}
 else if(k==='fandom'){event((v[1]||v[0]||'덕질 일정'),v[2]);todo(v[4],v[2]);}
 else if(k==='lifeAdmin'){event(v[0]||'생활 일정',v[1]);todo(v[4]||v[0],v[1]);if(v[6])event((v[0]||'생활 일정')+' 갱신',v[6]);}
 else if(k==='portfolio'){todo((v[0]||'포트폴리오')+' · '+(v[8]||'정리'),v[1]);}
 else if(k==='eventOps'){event(v[0]||'행사',v[1]);todo(v[5]||v[7]||v[3],v[1]);}
 else if(k==='petCare'){event((v[0]||'반려동물')+' 체크',v[1]);todo(v[2],v[1]);}
 else if(k==='independent'){event(v[0],v[1]);todo(v[4],v[1]);}
 else if(k==='couple'){event(v[0],v[1]);todo(v[4],v[1]);}
 else if(k==='routine'||k==='habitChallenge'){todo(v[0],v[1]);}
 else if(k==='fitness'){todo(v[7]||v[2],v[1]);}
 if(made.length){B().save();B().render(true);B().toast('PLANON '+Array.from(new Set(made)).join('·')+'에 연결했어요');}return made.length;}
function persistModal(m){var k=m.dataset.packModal,id=m.dataset.packId,vals=valuesFrom(m);if(!vals.some(Boolean)){B().toast('한 칸 이상 적어주세요');return null;}var rs=rows(k),r=rs.find(function(x){return x.id===id;});if(r){r.values=vals;r.updatedAt=Date.now();}else{r={id:id,values:vals,createdAt:Date.now(),updatedAt:Date.now()};rs.push(r);}B().save();return {k:k,r:r};}
function saveModal(){var m=document.querySelector('[data-pack-modal]');if(!m)return;var x=persistModal(m);if(!x)return;B().closeModal();B().render(true);setTimeout(inject,30);B().toast('팩 기록을 저장했어요');}
function linkModal(){var m=document.querySelector('[data-pack-modal]');if(!m)return;var x=persistModal(m);if(!x)return;var sig=JSON.stringify(x.r.values||[]);if(x.r.connectedHash===sig){B().toast('이 내용은 이미 플래너에 연결되어 있어요');return;}var d=DEF[x.k],dates=[];d.fields.forEach(function(f,i){if(f[1]==='date'&&val(x.r,i))dates.push(f[0]+' '+val(x.r,i));});B().openModal('<div class="pack-link-confirm"><small>PLANON에 연결</small><h3>무엇이 추가되는지 확인해 주세요</h3><p><b>'+esc(d.title)+'</b> 기록은 그대로 보관되고, 아래 내용만 기존 플래너에 추가돼요.</p><div class="pack-link-preview"><span>할 일 또는 일정</span><strong>'+esc(val(x.r,0)||d.title)+'</strong><small>'+esc(dates.join(' · ')||'날짜가 없는 항목은 오늘 할 일로 연결될 수 있어요')+'</small></div><p class="pack-safe-copy">팩을 나중에 해제해도 작성한 기록은 삭제되지 않아요.</p><div class="acts"><button class="b-ghost" data-act="close">취소</button><button class="b-save" data-pack-confirm-link="'+esc(x.k)+'" data-pack-confirm-id="'+esc(x.r.id)+'">확인하고 연결</button></div></div>');} 
function confirmLink(k,id){var r=rows(k).find(function(x){return x.id===id;});if(!r)return;var sig=JSON.stringify(r.values||[]);if(r.connectedHash===sig){B().toast('이 내용은 이미 플래너에 연결되어 있어요');return;}var can=connect(k,r);if(can){r.connectedHash=sig;B().save();B().closeModal();B().render(true);setTimeout(inject,30);}else B().toast('연결할 날짜나 작업 내용을 먼저 채워주세요');}
function del(id){var m=document.querySelector('[data-pack-modal]');if(!m)return;var k=m.dataset.packModal,rs=rows(k),i=rs.findIndex(function(x){return x.id===id;});if(i>=0)rs.splice(i,1);B().save();B().closeModal();B().render(true);setTimeout(inject,30);}
document.addEventListener('click',function(e){var a=e.target.closest&&e.target.closest('[data-pack-add],[data-pack-edit],[data-pack-save],[data-pack-link],[data-pack-delete],[data-pack-toggle-all],[data-pack-confirm-link]');if(!a)return;if(a.dataset.packConfirmLink)return confirmLink(a.dataset.packConfirmLink,a.dataset.packConfirmId);if(a.dataset.packAdd)return modal(a.dataset.packAdd);if(a.dataset.packEdit)return modal(a.dataset.packKey,a.dataset.packEdit);if(a.hasAttribute('data-pack-save'))return saveModal();if(a.hasAttribute('data-pack-link'))return linkModal();if(a.hasAttribute('data-pack-toggle-all')){store().homePrefs.showAll=!store().homePrefs.showAll;B().save();return inject();}if(a.dataset.packDelete)return del(a.dataset.packDelete);});
window.PLANON_FUNCTIONAL_PACKS={openDemo:function(k){if(!DEF[k])return;modal(k);var m=document.querySelector('[data-pack-modal]');if(m){m.classList.add('pack-demo-mode');var n=m.querySelector('.pack-link-note');if(n)n.innerHTML='<b>구매 전 화면 미리보기</b><span>입력 내용은 저장되지 않아요. 팩을 설치하면 이 작업판이 홈에 추가돼요.</span>';m.querySelectorAll('input,textarea,select').forEach(function(x){x.disabled=true;});var a=m.querySelector('.pack-modal-actions');if(a)a.innerHTML='<button class="b-save" data-act="close">미리보기 닫기</button>';}}};
window.addEventListener('planon-market-change',function(){setTimeout(inject,30);});var main=document.getElementById('main');if(main)new MutationObserver(function(){setTimeout(inject,0);}).observe(main,{childList:true,subtree:false});setTimeout(inject,200);
})();
