(function(){
'use strict';
var V={tab:'home',category:'all',query:'',detail:''};
function B(){return window.PLANON_UX_BRIDGE;}
function E(){return window.PLANON_MARKET_THEME;}
function D(){return window.PLANON_MARKET_CATALOG||{categories:{},products:[]};}
function P(){return window.PLANON_PAYMENT_ADAPTER;}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function money(n){n=Number(n||0);return n?'₩'+n.toLocaleString('ko-KR'):'무료';}
function market(){return E().state();}
function owned(p){return E().owned(p);}
function isAdmin(){return E().isAdmin();}
function pBy(id){return (D().products||[]).find(function(x){return x.id===id;});}
function wish(p){return (market().wishlist||[]).indexOf(p.id)>=0;}
function entitlementText(p){if(isAdmin()&&!p.isFree)return '관리자 보유';if(p.isFree||Number(p.price||0)===0)return '무료';if(owned(p))return '구매완료';return money(p.price);}
function swatch(p){var c=p.thumbnail&&p.thumbnail.colors||['#eee','#ddd','#ccc','#bbb'],pat=p.thumbnail&&p.thumbnail.pattern||'';return '<div class="market-thumb '+(pat?'pat-'+pat:'')+'" style="--m1:'+c[0]+';--m2:'+c[1]+';--m3:'+c[2]+';--m4:'+c[3]+'"><i></i><i></i><i></i></div>';}
function inject(){var b=B(),u=b&&b.ui&&b.ui(),main=document.getElementById('main');if(!main||!u||u.tab!=='settings'||u.settingsPage)return;if(main.querySelector('[data-planon-shop-entry]'))return;var sec=document.createElement('section');sec.className='card planon-shop-entry-card';sec.setAttribute('data-planon-shop-entry','1');sec.innerHTML='<button class="setrow chatrow" data-market-open><span>Planon Shop<small>테마 · 시간표 · 위젯 · 캐릭터 · 세팅팩</small></span><span class="chev">›</span></button>';var cards=main.querySelectorAll(':scope > section.card');if(cards.length>1)cards[1].before(sec);else main.appendChild(sec);}
function overlay(){var x=document.getElementById('planon-shop-overlay');if(!x){x=document.createElement('div');x.id='planon-shop-overlay';document.body.appendChild(x);}return x;}
function open(){V={tab:'home',category:'all',query:'',detail:''};overlay().className='open';render();}
function close(){E().clearPreview();var x=overlay();x.className='';x.innerHTML='';}
function filterProducts(){var xs=(D().products||[]).filter(function(p){return p.forSale!==false;});if(V.tab==='wish')xs=xs.filter(wish);if(V.tab==='owned')xs=xs.filter(owned);if(V.category!=='all')xs=xs.filter(function(p){return p.category===V.category;});var q=V.query.trim().toLowerCase();if(q)xs=xs.filter(function(p){return [p.name,p.description,(p.tags||[]).join(' '),p.creatorName].join(' ').toLowerCase().indexOf(q)>=0;});return xs;}
function categoryChips(){var c=D().categories||{},keys=['theme','timetable','background','icons','character','weeklyExport','frame','widget','preset','studyTemplate','bundle'];return '<div class="market-cats"><button class="'+(V.category==='all'?'on':'')+'" data-market-cat="all">전체</button>'+keys.map(function(k){return '<button class="'+(V.category===k?'on':'')+'" data-market-cat="'+k+'">'+esc(c[k]||k)+'</button>';}).join('')+'</div>';}
function productCard(p){return '<article class="market-product">'+swatch(p)+'<div class="market-product-copy"><div class="market-product-top"><span class="market-badge '+(owned(p)?'owned':'')+'">'+esc(entitlementText(p))+'</span><button class="market-wish '+(wish(p)?'on':'')+'" data-market-wish="'+p.id+'" aria-label="찜">☆</button></div><b>'+esc(p.name)+'</b><small>'+esc(p.creatorName||'Planon')+' · '+esc((D().categories||{})[p.category]||p.category)+'</small><p>'+esc(p.description)+'</p><button class="market-detail-btn" data-market-detail="'+p.id+'">보기</button></div></article>';}
function creatorBox(){return '<section class="market-creator-box"><div><b>Planon Creator / Market</b><p>지금은 공식 상점이에요. 나중에는 다른 사용자의 테마·세팅도 판매할 수 있게 상품 구조를 미리 열어뒀어요.</p></div><button data-market-creator>내 디자인 판매하기</button></section>';}
function historyHTML(){var rows=(market().purchaseLog||[]).slice().sort(function(a,b){return Number(b.purchasedAt||0)-Number(a.purchasedAt||0);});return '<div class="market-history">'+(rows.length?rows.map(function(r){var p=pBy(r.productId),d=r.purchasedAt?new Date(r.purchasedAt):null;return '<div class="market-history-row"><span><b>'+esc(p?p.name:r.productId)+'</b><small>'+esc(d&&!isNaN(d)?d.toLocaleString('ko-KR'):'구매 기록')+' · '+esc(r.provider||'')+'</small></span><strong>'+money(r.amount)+'</strong></div>';}).join(''):'<div class="market-empty">아직 구매한 상품이 없어요.</div>')+'</div>';}
function listHTML(){if(V.tab==='history')return historyHTML();var xs=filterProducts();return '<div class="market-grid">'+(xs.length?xs.map(productCard).join(''):'<div class="market-empty">조건에 맞는 상품이 없어요.</div>')+'</div>';}
function headStatus(){var a=E().account();return isAdmin()?'<span class="market-admin">관리자 · 전체 상품 보유</span>':(a.loggedIn?'<span class="market-sync">계정 구매내역 동기화</span>':'<span class="market-sync">무료 상품은 바로 적용 · 구매는 로그인 후</span>');}
function homeHTML(){return '<div class="market-shell"><header class="market-head"><button data-market-close aria-label="닫기">‹</button><div><h2>Planon Shop</h2><small>플래너는 무료 그대로 · 꾸미기와 세팅만 선택</small></div>'+headStatus()+'</header><div class="market-tools"><input id="market-search" value="'+esc(V.query)+'" placeholder="테마·위젯·세팅 검색"><button data-market-restore>구매 복원</button></div><nav class="market-tabs"><button class="'+(V.tab==='home'?'on':'')+'" data-market-tab="home">추천</button><button class="'+(V.tab==='wish'?'on':'')+'" data-market-tab="wish">찜 '+(market().wishlist||[]).length+'</button><button class="'+(V.tab==='owned'?'on':'')+'" data-market-tab="owned">보유함</button><button class="'+(V.tab==='history'?'on':'')+'" data-market-tab="history">구매내역</button></nav>'+(V.tab==='history'?'':categoryChips())+'<div class="market-note"><b>핵심 생산성 기능은 무료</b><span>시간표·할 일·시험·일정·친구·백업·자동배치는 상품 구매 여부와 관계없이 그대로 사용할 수 있어요.</span></div>'+listHTML()+creatorBox()+'<div class="market-footer-actions"><button data-market-reset>기존 플래논 디자인으로 돌아가기</button>'+(market().lastPresetBackup?'<button data-market-undo-preset>세팅팩 적용 전으로 되돌리기</button>':'')+'</div></div>';}
function detailHTML(p){var parts=(p.bundleItems||[]).map(pBy).filter(Boolean);var prev=['theme','timetable','background','icons','character','widget','frame','weeklyExport','bundle'].indexOf(p.productType)>=0;var action='';if(owned(p)){action='<button class="market-apply" data-market-apply="'+p.id+'">'+(p.productType==='bundle'?'구성 전체 적용':'적용하기')+'</button>';}else if(Number(p.price||0)>0){action='<button class="market-buy" data-market-buy="'+p.id+'">구매하기 · '+money(p.price)+'</button>';}else action='<button class="market-apply" data-market-apply="'+p.id+'">적용하기</button>';return '<div class="market-detail-sheet"><button class="market-detail-close" data-market-detail-close>✕</button>'+swatch(p)+'<span class="market-badge '+(owned(p)?'owned':'')+'">'+esc(entitlementText(p))+'</span><h3>'+esc(p.name)+'</h3><small>'+esc(p.creatorName||'Planon')+' · '+esc((D().categories||{})[p.category]||p.category)+'</small><p>'+esc(p.description)+'</p>'+(parts.length?'<div class="market-bundle-list"><b>포함 상품</b>'+parts.map(function(x){return '<span>'+esc(x.name)+'</span>';}).join('')+'</div>':'')+(p.payload&&p.payload.templateNote?'<div class="market-template-note">'+esc(p.payload.templateNote)+'</div>':'')+'<div class="market-detail-actions">'+(prev?'<button data-market-preview="'+p.id+'">10초 미리 적용</button>':'')+action+'<button class="market-wish-text" data-market-wish="'+p.id+'">'+(wish(p)?'찜 해제':'찜하기')+'</button></div>'+(P().mode==='test'&&Number(p.price||0)>0&&!owned(p)?'<p class="market-test-note">현재 베타에서는 실제 결제 없이 구매 흐름만 테스트해요. 나중에 결제 모듈만 교체할 수 있게 분리해뒀어요.</p>':'')+'</div>';}
function render(){var x=overlay();if(!x.classList.contains('open'))return;x.innerHTML=homeHTML()+(V.detail&&pBy(V.detail)?'<div class="market-detail-backdrop">'+detailHTML(pBy(V.detail))+'</div>':'');var s=document.getElementById('market-search');if(s)s.addEventListener('input',function(){V.query=s.value;var g=x.querySelector('.market-grid');if(g)g.outerHTML=listHTML();});}
function save(){var b=B();if(b&&b.save)b.save();}
function toggleWish(id){var m=market(),i=m.wishlist.indexOf(id);if(i>=0)m.wishlist.splice(i,1);else m.wishlist.push(id);save();render();}
function goLogin(){close();var b=B(),u=b&&b.ui&&b.ui();if(u){u.tab='settings';u.settingsPage='account';b.render(true);if(b.toast)b.toast('구매 기록을 계정에 보관하려면 먼저 로그인해주세요');}}
function purchase(id){var p=pBy(id);if(!p)return;if(!E().account().loggedIn&&!isAdmin()){goLogin();return;}if(!confirm('현재는 실제 결제 없이 구매 흐름만 테스트해요.\n\n'+p.name+'을(를) 보유함에 추가할까요?'))return;P().purchase(p).then(function(rec){var m=market();if(m.owned.indexOf(p.id)<0)m.owned.push(p.id);m.purchaseLog.push(rec);save();if(B().toast)B().toast('구매완료 · 보유함에 추가했어요');render();}).catch(function(e){if(String(e&&e.message)==='LOGIN_REQUIRED')goLogin();else if(B().toast)B().toast('구매 테스트를 완료하지 못했어요');});}
function apply(id){var p=pBy(id);if(!p)return;if(!owned(p)){purchase(id);return;}if(E().activate(p)){if(B().toast)B().toast(p.name+' 적용 완료');render();}}
function restore(){P().restore().then(function(){if(B().toast)B().toast(isAdmin()?'관리자 계정은 모든 상품을 자동 보유해요':'구매내역은 플래논 계정 데이터와 함께 자동 복원돼요');render();});}
function creator(){var d=market().creatorDraft||{};var b=B();b.openModal('<h3>Planon Creator 신청</h3><p class="hint">아직 정산·판매자 기능은 열지 않았어요. 어떤 상품을 만들고 싶은지 먼저 검증하는 신청폼이에요.</p><input class="fld" id="market-creator-name" maxlength="30" placeholder="표시 이름" value="'+esc(d.name||'')+'"><select class="fld" id="market-creator-type"><option>테마</option><option>시간표 디자인</option><option>위젯</option><option>캐릭터</option><option>플래너 세팅</option><option>공부 템플릿</option></select><textarea class="fld" id="market-creator-desc" maxlength="500" placeholder="어떤 상품을 만들고 싶은지 적어주세요">'+esc(d.desc||'')+'</textarea><div class="acts"><button class="b-ghost" data-market-creator-save>임시 저장</button><button class="b-save" data-market-creator-copy>신청 내용 복사</button></div>');}
function creatorData(){return {name:(document.getElementById('market-creator-name')||{}).value||'',type:(document.getElementById('market-creator-type')||{}).value||'',desc:(document.getElementById('market-creator-desc')||{}).value||''};}
function saveCreator(copy){var m=market(),d=creatorData();m.creatorDraft=d;save();if(copy){var t='[Planon Creator 신청]\n이름: '+d.name+'\n상품 종류: '+d.type+'\n아이디어: '+d.desc;try{navigator.clipboard.writeText(t).then(function(){B().toast('신청 내용을 복사했어요');},function(){B().toast('임시 저장했어요');});}catch(e){B().toast('임시 저장했어요');}}else B().toast('Creator 신청 초안을 저장했어요');}
document.addEventListener('click',function(e){var a=e.target.closest&&e.target.closest('button,[data-market-open]');if(!a)return;if(a.hasAttribute('data-market-open')){open();return;}if(a.hasAttribute('data-market-close')){close();return;}if(a.dataset.marketTab){V.tab=a.dataset.marketTab;V.category='all';render();return;}if(a.dataset.marketCat){V.category=a.dataset.marketCat;render();return;}if(a.dataset.marketDetail){V.detail=a.dataset.marketDetail;render();return;}if(a.hasAttribute('data-market-detail-close')){V.detail='';E().clearPreview();render();return;}if(a.dataset.marketWish){toggleWish(a.dataset.marketWish);return;}if(a.dataset.marketPreview){E().preview(pBy(a.dataset.marketPreview),10000);return;}if(a.dataset.marketApply){apply(a.dataset.marketApply);return;}if(a.dataset.marketBuy){purchase(a.dataset.marketBuy);return;}if(a.hasAttribute('data-market-restore')){restore();return;}if(a.hasAttribute('data-market-reset')){E().resetVisual();B().toast('기존 플래논 디자인으로 돌아왔어요');render();return;}if(a.hasAttribute('data-market-undo-preset')){if(E().undoPreset())B().toast('세팅팩 적용 전으로 돌아왔어요');render();return;}if(a.hasAttribute('data-market-creator')){creator();return;}if(a.hasAttribute('data-market-creator-save')){saveCreator(false);return;}if(a.hasAttribute('data-market-creator-copy')){saveCreator(true);return;}});
var main=document.getElementById('main');if(main)new MutationObserver(function(){setTimeout(inject,20);}).observe(main,{childList:true});
window.PLANON_SHOP={open:open,render:render};inject();
})();