(function(){
'use strict';
var preview=null,previewTimer=null;
function B(){return window.PLANON_UX_BRIDGE;}
function catalog(){return window.PLANON_MARKET_CATALOG||{products:[]};}
function product(id){return (catalog().products||[]).find(function(x){return x.id===id;})||null;}
function state(){var b=B(),s=b&&b.state&&b.state();if(!s)return null;s.settings=s.settings||{};var m=s.settings.market;if(!m||typeof m!=='object')m=s.settings.market={};if(!Array.isArray(m.owned))m.owned=[];if(!Array.isArray(m.wishlist))m.wishlist=[];if(!Array.isArray(m.purchaseLog))m.purchaseLog=[];if(!Array.isArray(m.legacyEntitlements))m.legacyEntitlements=[];if(!m.active||typeof m.active!=='object')m.active={};/* 캐릭터 테마는 한 번에 하나만. 먼별/먼돌이 활성화되어 있으면 예전 네모 캐릭터 스킨은 같이 켜지지 않게 정리한다. 배경/색상 테마는 별도 슬롯이라 유지. */if(m.active.meonbyeol&&m.active.character)delete m.active.character;return m;}
function account(){var b=B();return b&&b.account?b.account():{uid:'',email:'',loggedIn:false};}
function isAdmin(){return String(account().email||'').trim().toLowerCase()==='clover_cys@naver.com';}
function bundleOwns(id,m){return (m.owned||[]).some(function(bid){var bp=product(bid);return bp&&(bp.bundleItems||[]).indexOf(id)>=0;});}
function rawOwn(id,m){return (m.owned||[]).indexOf(id)>=0||(m.legacyEntitlements||[]).indexOf(id)>=0||bundleOwns(id,m);}
/* 먼별 권한 별칭: 뽑기형·선택형·예전 먼별 테마 중 무엇을 샀든 '먼별 테마'는 보유. 선택형은 뽑기형도 포함. */
var MB_ALIAS={'meonbyeol-theme':['meonbyeol-random','meonbyeol-pick'],'meonbyeol-random':['meonbyeol-theme','meonbyeol-pick']};
function owned(p){if(!p)return false;var m=state()||{};if(isAdmin()||p.isFree||Number(p.price||0)===0||rawOwn(p.id,m))return true;return (MB_ALIAS[p.id]||[]).some(function(id){return rawOwn(id,m);});}
/* 이미 먼별을 가진 사람이 선택형을 사면 차액만. 보유 상품은 0원(재결제 없음). */
function priceFor(p){if(!p)return 0;if(owned(p))return 0;var P=(catalog().prices||{});if(p.id==='meonbyeol-pick'&&owned(product('meonbyeol-theme')))return Math.max(0,Number(P.meonbyeolPick||p.price)-Number(P.meonbyeolRandom||9900));return Number(p.price||0);}
/* 3일 무료체험: 계정 설정(settings.market.trials)에 남아 기기를 바꿔도 한 번만. */
var TRIAL_MS=3*864e5;
function trialInfo(key){var m=state();return m&&m.trials&&m.trials[key]||null;}
function trialActive(key){var t=trialInfo(key);return !!(t&&Number(t.end)>Date.now());}
function startTrial(key){var m=state();if(!m)return false;if(!m.trials||typeof m.trials!=='object')m.trials={};if(m.trials[key])return false;var now=Date.now();m.trials[key]={start:now,end:now+TRIAL_MS};var b=B();if(b&&b.save)b.save();return true;}
/* 유료 꾸미기를 하나라도 가진 사람(또는 먼별 체험 중) = 프리미엄: 집중 기록·주간 그리드가 열려요. */
function hasPremium(){if(isAdmin())return true;var m=state()||{};if(trialActive('meonbyeol')||trialActive('meondol'))return true;return (catalog().products||[]).some(function(p){return !p.isFree&&Number(p.price||0)>0&&rawOwn(p.id,m);});}
function legacyProduct(kind,val){val=String(val||'').toLowerCase();return (catalog().products||[]).find(function(p){if(kind==='color')return String(p.legacyColor||'').toLowerCase()===val;if(kind==='background')return String(p.legacyBg||'')===val;return false;})||null;}
function canUseLegacy(kind,val){if(kind==='background'&&(val==='plain'||val==='rainbow'||!val))return true;var p=legacyProduct(kind,val);return !p||owned(p);}
function requireLegacy(kind,val){var p=legacyProduct(kind,val);if(!p||owned(p))return true;try{if(window.PLANON_SHOP&&typeof window.PLANON_SHOP.openProduct==='function')window.PLANON_SHOP.openProduct(p.id);else if(B()&&B().toast)B().toast('Planon Shop에서 구매 후 적용할 수 있어요');}catch(e){}return false;}
function grandfatherLegacy(){var b=B(),s=b&&b.state&&b.state(),m=state();if(!s||!m||m.legacyDesignChecked)return;var got=[];var cp=legacyProduct('color',s.settings&&s.settings.defColor),bp=legacyProduct('background',s.settings&&s.settings.bg);[cp,bp].forEach(function(p){if(p&&!p.isFree&&Number(p.price||0)>0&&(m.legacyEntitlements||[]).indexOf(p.id)<0){m.legacyEntitlements.push(p.id);got.push(p.id);}});m.legacyDesignChecked=true;if(b&&b.save)b.save();}
function varsFromTheme(t){if(!t)return '';var v=[];function add(k,val){if(val)v.push(k+':'+val+' !important');}add('--bg',t.background);add('--planner-color',t.primary);add('--accent',t.primary);add('--soft',t.secondary);add('--card',t.card);add('--market-schedule',t.schedule);add('--line',t.border);add('--market-button',t.button);add('--market-icon',t.icon);add('--ink',t.ink);add('--sub',t.sub);return v.join(';');}
function activeProduct(type,override){var m=state()||{},id=override&&override[type]!==undefined?override[type]:(m.active||{})[type];return product(id);}
function buildStyle(override){
  var th=activeProduct('theme',override),bg=activeProduct('background',override),tt=activeProduct('timetable',override),ic=activeProduct('icons',override),ch=activeProduct('character',override),wg=activeProduct('widget',override),fr=activeProduct('frame',override);
  var css='';
  if(th&&owned(th)&&th.payload&&th.payload.theme){css+=':root[data-planon-market="1"]{'+varsFromTheme(th.payload.theme)+'}\n';css+=':root[data-planon-market="1"] .tbtn,:root[data-planon-market="1"] .ibtn{background:var(--market-button,var(--soft))!important}\n';css+=':root[data-planon-market="1"] .plus,:root[data-planon-market="1"] .b-save{background:var(--planner-color)!important;color:var(--planner-ink,#1c1c1e)!important}\n';css+=':root[data-planon-market="1"] .hchip.ev,:root[data-planon-market="1"] .blk{border-color:var(--market-schedule,var(--planner-color))!important}\n';css+=':root[data-planon-market="1"] input[type="checkbox"]{accent-color:var(--planner-color)!important}\n';}
  if(bg&&owned(bg)&&bg.payload&&bg.payload.background){var b=bg.payload.background,sz=Number(b.size||36);css+=':root[data-planon-market="1"] body{background-color:'+b.color+'!important;background-image:radial-gradient(circle,'+b.dot+' 3px,transparent 3.6px),radial-gradient(circle,'+b.dot+' 3px,transparent 3.6px)!important;background-size:'+sz+'px '+sz+'px!important;background-position:0 0,'+(sz/2)+'px '+(sz/2)+'px!important;background-repeat:repeat!important}\n';}
  if(tt&&owned(tt)){var s=tt.payload&&tt.payload.timetableStyle;if(s==='check'){css+=':root[data-planon-market="1"] .tt-card{background-image:linear-gradient(90deg,color-mix(in srgb,var(--line) 45%,transparent) 1px,transparent 1px),linear-gradient(color-mix(in srgb,var(--line) 45%,transparent) 1px,transparent 1px)!important;background-size:22px 22px!important}:root[data-planon-market="1"] .tt .blk{border-radius:13px!important;box-shadow:0 2px 0 color-mix(in srgb,var(--ink) 7%,transparent)!important}\n';}if(s==='cozy'){css+=':root[data-planon-market="1"] .tt-card{background:color-mix(in srgb,#fff4df 55%,var(--card))!important}:root[data-planon-market="1"] .tt .blk{border-radius:15px!important;border:1px solid color-mix(in srgb,var(--c) 55%,#8b7254)!important;box-shadow:0 4px 12px color-mix(in srgb,#7b6247 8%,transparent)!important}\n';}}
  if(ic&&owned(ic)&&ic.payload&&ic.payload.iconStyle==='soft'){css+=':root[data-planon-market="1"] input[type="checkbox"]{width:19px;height:19px;border-radius:7px!important}:root[data-planon-market="1"] .ck input{accent-color:var(--planner-color)!important}:root[data-planon-market="1"] .todo .check{border-radius:9px!important}\n';}
  if(ch&&owned(ch)&&ch.payload&&ch.payload.characterStyle==='ribbon'){css+=':root[data-planon-market="1"] .nemo-char{position:relative;overflow:visible}:root[data-planon-market="1"] .nemo-char:after{content:"";position:absolute;left:2px;top:4px;width:10px;height:7px;border-radius:70% 35% 70% 35%;background:color-mix(in srgb,var(--planner-color) 55%,#b65f78 45%);transform:rotate(-20deg);box-shadow:8px 2px 0 color-mix(in srgb,var(--planner-color) 55%,#b65f78 45%);pointer-events:none}:root[data-planon-market="1"] .story-avatar-friend .nemo-char:after,:root[data-planon-market="1"] .story-pair-friend .nemo-char:after,:root[data-planon-market="1"] .fav .nemo-char:after,:root[data-planon-market="1"] .story-reaction-nemo:after{content:none!important;display:none!important}\n';}
  if(wg&&owned(wg)&&wg.payload&&wg.payload.widgetStyle==='label'){css+=':root[data-planon-market="1"] .home-hero,:root[data-planon-market="1"] .home-summary,:root[data-planon-market="1"] .dayg>.side>.card{border-width:1.5px!important;border-color:color-mix(in srgb,var(--planner-color) 52%,var(--line))!important;box-shadow:0 5px 18px color-mix(in srgb,var(--planner-color) 10%,transparent)!important}\n';}
  if(fr&&owned(fr)&&fr.payload&&fr.payload.frameStyle==='polaroid'){css+=':root[data-planon-market="1"] .retrobox,:root[data-planon-market="1"] .diary-entry-note,:root[data-planon-market="1"] .diary-book-inner{border:1px solid color-mix(in srgb,var(--planner-color) 34%,var(--line))!important;box-shadow:0 7px 18px rgba(60,45,30,.07)!important;background:color-mix(in srgb,var(--card) 90%,#fff 10%)!important}\n';}
  return css;
}
function renderStyle(override){var st=document.getElementById('planon-market-runtime-style');if(!st){st=document.createElement('style');st.id='planon-market-runtime-style';document.head.appendChild(st);}st.textContent=buildStyle(override);var any=st.textContent.trim().length>0;if(any)document.documentElement.setAttribute('data-planon-market','1');else document.documentElement.removeAttribute('data-planon-market');}
function reapply(){renderStyle(preview&&preview.override||null);}
function fire(){try{window.dispatchEvent(new Event('planon-market-change'));}catch(e){}}
function saveRender(){var b=B();if(b&&b.save)b.save();if(b&&b.render)b.render();setTimeout(reapply,0);setTimeout(fire,0);}
function deactivate(type,id){var m=state();if(!m)return;if(type==='functionalPack'){m.activeFunctionalPacks=(m.activeFunctionalPacks||[]).filter(function(x){return x!==id;});if(m.active&&m.active.functionalPack===id)delete m.active.functionalPack;}else delete m.active[type];saveRender();}
function setActive(type,id){var m=state();if(!m)return false;var p=product(id);if(!p||!owned(p))return false;if(type==='functionalPack'){m.activeFunctionalPacks=m.activeFunctionalPacks||[];if(m.activeFunctionalPacks.indexOf(id)<0)m.activeFunctionalPacks.push(id);}/* character와 meonbyeol은 같은 '캐릭터 슬롯'으로 취급. 둘 중 하나를 켜면 다른 하나는 해제. background/theme은 건드리지 않는다. */if(type==='meonbyeol')delete m.active.character;else if(type==='character')delete m.active.meonbyeol;m.active[type]=id;saveRender();return true;}
function clearPreview(){if(previewTimer)clearTimeout(previewTimer);previewTimer=null;preview=null;reapply();fire();var n=document.getElementById('planon-market-preview-pill');if(n)n.remove();}
function previewProduct(){/* 상점 미리보기는 사용하지 않는다. 먼별/먼돌은 3일 무료체험으로 실제 앱에서 확인. */return false;}
function applyPreset(p){if(!p||!owned(p)||!p.payload||!p.payload.settings)return false;var b=B(),s=b&&b.state&&b.state(),m=state();if(!s||!m)return false;var keys=Object.keys(p.payload.settings),backup={};keys.forEach(function(k){backup[k]=s.settings[k];s.settings[k]=JSON.parse(JSON.stringify(p.payload.settings[k]));});m.lastPresetBackup={at:Date.now(),productId:p.id,settings:backup};m.active[p.productType]=p.id;saveRender();return true;}
function undoPreset(){var b=B(),s=b&&b.state&&b.state(),m=state();if(!s||!m||!m.lastPresetBackup)return false;var x=m.lastPresetBackup;Object.keys(x.settings||{}).forEach(function(k){s.settings[k]=x.settings[k];});delete m.lastPresetBackup;delete m.active.preset;delete m.active.studyTemplate;saveRender();return true;}
function activate(p){if(!p||!owned(p))return false;var b=B(),s=b&&b.state&&b.state(),m=state();if(p.productType==='preset'||p.productType==='studyTemplate')return applyPreset(p);if(p.productType==='bundle'){(p.bundleItems||[]).forEach(function(id){var q=product(id);if(!q||q.productType==='preset'||q.productType==='studyTemplate')return;if(q.productType==='functionalPack'){m.activeFunctionalPacks=m.activeFunctionalPacks||[];if(m.activeFunctionalPacks.indexOf(q.id)<0)m.activeFunctionalPacks.push(q.id);m.active.functionalPack=q.id;return;}if(q.productType==='meonbyeol')delete m.active.character;else if(q.productType==='character')delete m.active.meonbyeol;m.active[q.productType]=q.id;});saveRender();return true;}if(p.legacyColor&&s&&s.settings){s.settings.defColor=p.legacyColor;try{localStorage.setItem('planner.defColor',p.legacyColor);}catch(e){}m.active.theme=p.id;saveRender();return true;}if(p.legacyBg&&s&&s.settings){s.settings.bg=p.legacyBg;try{localStorage.setItem('planner.bg',p.legacyBg);}catch(e){}m.active.background=p.id;saveRender();return true;}if(p.productType==='meonbyeol')return setActive('meonbyeol',p.id==='meondol-theme'?'meondol-theme':'meonbyeol-theme');if(p.productType==='wardrobe'||p.productType==='meonbyeolEgg')return true;return setActive(p.productType,p.id);}
function resetVisual(){var m=state();if(!m)return;['theme','background','timetable','icons','character','meonbyeol','widget','frame','weeklyExport'].forEach(function(k){delete m.active[k];});saveRender();}
function exportStyle(){var p=activeProduct('weeklyExport',preview&&preview.override);return p&&owned(p)&&p.payload?p.payload.exportStyle||null:null;}

function decorateLegacyLocks(){
  document.querySelectorAll('[data-act="set-defcolor"]').forEach(function(b){var locked=!canUseLegacy('color',b.dataset.v);b.classList.toggle('market-locked',locked);if(locked)b.title='Planon Shop 유료 컬러';else if(b.title==='Planon Shop 유료 컬러')b.removeAttribute('title');});
  document.querySelectorAll('[data-act="set-bg"]').forEach(function(b){var locked=!canUseLegacy('background',b.dataset.v);b.classList.toggle('market-locked',locked);if(locked)b.title='Planon Shop 유료 배경';else if(b.title==='Planon Shop 유료 배경')b.removeAttribute('title');});
}
document.addEventListener('click',function(e){var a=e.target&&e.target.closest?e.target.closest('[data-act="set-defcolor"],[data-act="set-bg"]'):null;if(!a)return;var kind=a.dataset.act==='set-defcolor'?'color':'background';if(canUseLegacy(kind,a.dataset.v)){var m=state();if(m&&m.active){if(kind==='color')delete m.active.theme;else delete m.active.background;}return;}e.preventDefault();e.stopImmediatePropagation();requireLegacy(kind,a.dataset.v);},true);

window.PLANON_MARKET_THEME={previewOverride:function(){return null;},deactivate:deactivate,state:state,account:account,isAdmin:isAdmin,owned:owned,product:product,activate:activate,preview:previewProduct,clearPreview:clearPreview,reapply:reapply,resetVisual:resetVisual,undoPreset:undoPreset,exportStyle:exportStyle,legacyProduct:legacyProduct,canUseLegacy:canUseLegacy,requireLegacy:requireLegacy,grandfatherLegacy:grandfatherLegacy,priceFor:priceFor,trialInfo:trialInfo,trialActive:trialActive,startTrial:startTrial,hasPremium:hasPremium,rawOwn:function(id){return rawOwn(id,state()||{});}};
setTimeout(function(){grandfatherLegacy();reapply();decorateLegacyLocks();},0);
var main=document.getElementById('main');if(main)new MutationObserver(function(){setTimeout(function(){reapply();decorateLegacyLocks();},0);}).observe(main,{childList:true,subtree:false});
})();